import type { LineTypeDef } from "@/types/line";

/**
 * §2.8–§2.9 catalog. Boundary lines (§2.8 Хүснэгт 11) are visually identical
 * across all 10 echelons — only the repeating echelon letter differs — so
 * they're modeled as one drawable type with an echelon picked at draw time,
 * rather than 10 near-duplicate entries.
 */
export const LINE_TYPES: LineTypeDef[] = [
  {
    id: "boundary",
    kind: "boundary",
    mn: "Хязгаарлах шугам",
    desc: "Хөрш анги, нэгжийн хариуцах бүсийг ялган зааглах шугам. Шатлалыг сонгоно.",
    ref: "Т4-2022 §2.8 Хүснэгт 11",
  },
  {
    id: "mainStrike",
    kind: "strikeDirection",
    mn: "Гол цохилтын чиглэл",
    desc: "Гол хүчний довтолгооны үндсэн чиглэл.",
    ref: "Т4-2022 §2.9",
  },
  {
    id: "supportStrike",
    kind: "strikeDirection",
    mn: "Туслах цохилтын чиглэл",
    desc: "Туслах хүчний довтолгооны чиглэл.",
    ref: "Т4-2022 §2.9",
    dashed: true,
  },
  {
    id: "furtherAdvance",
    kind: "strikeDirection",
    mn: "Цаашид давших чиглэл",
    desc: "Объект эзэлсний дараа цаашид үргэлжлүүлэн давших чиглэл (ЦДЧ).",
    ref: "Т4-2022 §2.9",
  },
  {
    id: "immediateMission",
    kind: "missionLine",
    mn: "Ойрын үүрэг",
    desc: "Анги, нэгжийн ойрын үүргийг заасан шугам.",
    ref: "Т4-2022 §2.9",
  },
  {
    id: "subsequentMission",
    kind: "missionLine",
    mn: "Дараагийн үүрэг",
    desc: "Анги, нэгжийн дараагийн үүргийг заасан шугам.",
    ref: "Т4-2022 §2.9",
  },
  {
    id: "directFireZone",
    kind: "plainLine",
    mn: "Шууд хөнөөлийн бүс",
    desc: "Шууд харах, шууд буудлагын зэвсгийн хөнөөх зайн хил (ШХБ).",
    ref: "Т4-2022 §2.9",
  },
  {
    id: "restrictedArea",
    kind: "plainLine",
    mn: "Хориглолтын район",
    desc: "Батальон/ротын хориглолтын районы хариуцлагын бүсийн төгсгөлийг заасан шугам.",
    ref: "Т4-2022 §2.9",
  },
  {
    id: "restrictedInnerLine",
    kind: "plainLine",
    mn: "Хориглолтын өвөр эгнээ",
    desc: "Хориглолтын районы дотоод эгнээг заасан шугам, газар орны шинж чанараас хамааран хаяалбарын дагуу зурна.",
    ref: "Т4-2022 §2.9",
  },
  {
    id: "strongpointSubunit",
    kind: "plainLine",
    mn: "Тулгуурт байр эзэлсэн салбар",
    desc: "Тулгуурт байр эзэлсэн салбарыг өвөр эгнээг хаяалбарын дагуу заасан шугам.",
    ref: "Т4-2022 §2.9",
  },
  {
    id: "combatArea",
    kind: "area",
    mn: "Анги, салбарын байрлалын район",
    desc: "Анги, салбарын байрлалын район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "assemblyArea",
    kind: "area",
    mn: "Цугларах район",
    desc: "Анги, нэгж цугларах район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "mobilizationArea",
    kind: "area",
    mn: "Дайчилгааны район",
    desc: "Дайчилгаа хийх район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "startArea",
    kind: "area",
    mn: "Эхлэх район",
    desc: "Ажиллагаа эхлэх район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "overnightArea",
    kind: "area",
    mn: "Хоноглолт хийх район (марш)",
    desc: "Марш хийх үед хоноглолт хийх район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "restArea",
    kind: "area",
    mn: "Өнжилт хийх район (марш)",
    desc: "Марш хийх үед өнжилт хийх район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "reserveArea",
    kind: "area",
    mn: "Нөөц хүч байрлуулах район",
    desc: "Нөөц хүч байрлуулах район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "fireArea",
    kind: "area",
    mn: "Галын уут байгуулах район",
    desc: "Дайсныг татан оруулж бөглөх галын уут байгуулах район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "combingArea",
    kind: "area",
    mn: "Самнах ажиллагааны район",
    desc: "Мотобуудлагын рот самнах ажиллагаа явуулж байгаа район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "airDropArea",
    kind: "area",
    mn: "Шүхэр десантаар буух район",
    desc: "Шүхэр ашиглан десантаар буух район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "specialAttentionArea",
    kind: "area",
    mn: "Онцгой анхаарах район",
    desc: "Онцгой анхаарал шаардсан район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
    dashed: true,
  },
  {
    id: "artilleryFiringArea",
    kind: "area",
    mn: "Артиллери, зенитийн галт байрны район",
    desc: "Артиллери, зенитийн пуужингийн нэгтгэл, ангийн галт байрны район.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "floodedArea",
    kind: "area",
    mn: "Усанд автсан бүс",
    desc: "Усанд автсан бүс нутаг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
    dashed: true,
  },
  {
    id: "stateBorder",
    kind: "plainLine",
    mn: "Улсын хил",
    desc: "Улсын хилийн шугам.",
    ref: "Т4-2022 Хавсралт 17",
  },
  {
    id: "borderZone",
    kind: "plainLine",
    mn: "Хилийн бүс",
    desc: "Хилийн бүсийн шугам.",
    ref: "Т4-2022 Хавсралт 17",
    dashed: true,
  },
  {
    id: "protectiveZone1",
    kind: "plainLine",
    mn: "Хамгаалалтын I зааг, бүс",
    desc: "Онцгой байдлын хамгаалалтын нэгдүгээр зааг, бүс.",
    ref: "Т4-2022 §16.2/16.3",
  },
  {
    id: "protectiveZone2",
    kind: "plainLine",
    mn: "Хамгаалалтын II зааг, бүс",
    desc: "Онцгой байдлын хамгаалалтын хоёрдугаар зааг, бүс.",
    ref: "Т4-2022 §16.2/16.3",
  },
  {
    id: "protectiveZone3",
    kind: "plainLine",
    mn: "Хамгаалалтын III зааг, бүс",
    desc: "Онцгой байдлын хамгаалалтын гуравдугаар зааг, бүс.",
    ref: "Т4-2022 §16.2/16.3",
  },

  // ───── §2.9 Хүснэгт 12 — тагнах бүс, хүч задлах болон бусад зааг ─────
  {
    id: "threatCapabilityZone",
    kind: "plainLine",
    mn: "Чадавхад заналхийллийн бүс (ЧЗХБ)",
    desc: "Дайсны чадавхад заналхийлэх бүсийн зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "detailedReconZone",
    kind: "plainLine",
    mn: "Нарийвчлан тагнах бүс (НТБ)",
    desc: "Нарийвчлан тагнах бүсийн зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "generalReconZone",
    kind: "plainLine",
    mn: "Тоймлон тагнах бүс (ТТБ)",
    desc: "Тоймлон тагнах бүсийн зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "startLine",
    kind: "plainLine",
    mn: "Эхлэх зааг",
    desc: "Ажиллагаа эхлэх зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "possibleContactLine",
    kind: "plainLine",
    mn: "Дайсантай тулгарч болзошгүй зааг",
    desc: "Дайсантай тулгарч болзошгүй зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
    dashed: true,
  },
  {
    id: "occupiedLine",
    kind: "plainLine",
    mn: "Анги, салбаруудын эзэлсэн зааг",
    desc: "Анги, салбаруудын эзэлсэн зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "battalionDeployLine",
    kind: "plainLine",
    mn: "Батальоны цуваанд хүч задлах зааг",
    desc: "Батальоны цуваанд хүч задлах зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "companyDeployLine",
    kind: "plainLine",
    mn: "Ротын цуваанд хүч задлах зааг",
    desc: "Ротын цуваанд хүч задлах зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "platoonDeployLine",
    kind: "plainLine",
    mn: "Салааны цуваанд хүч задлах зааг",
    desc: "Салааны цуваанд хүч задлах зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "attackLine",
    kind: "plainLine",
    mn: "Атаканд орох зааг",
    desc: "Атаканд орох зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "dismountLine",
    kind: "plainLine",
    mn: "Мотобуудлагын салбарын явгалах зааг",
    desc: "Мотобуудлагын салбар техникээс буун явгалах зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "antitankReserveLine",
    kind: "plainLine",
    mn: "Танк эсэргүүцэх нөөц хүч задлах зааг",
    desc: "Танк эсэргүүцэх нөөц хүч задлах зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "fireLine",
    kind: "plainLine",
    mn: "Галын зааг",
    desc: "Галын зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "breakthroughSector",
    kind: "strikeDirection",
    mn: "Цөмлөх хэсэг",
    desc: "Хамгаалалтыг цөмлөх хэсэг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "attackRepulsedLine",
    kind: "plainLine",
    mn: "Атак няцаагдсан зааг",
    desc: "Атак няцаагдсан зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },
  {
    id: "withdrawnLine",
    kind: "plainLine",
    mn: "Тухайн заагаас ухарсан зааг",
    desc: "Тухайн заагаас ухарсан зааг.",
    ref: "Т4-2022 §2.9 Хүснэгт 12",
  },

  // ───── Хавсралт 17 (§16.1) — Хилийн цэргийн зааг, шугам ─────
  {
    id: "borderDetachmentJunction",
    kind: "plainLine",
    mn: "Хилийн отрядын уулзвар",
    desc: "Хилийн отрядуудын хариуцах хэсгийн уулзвар.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
  },
  {
    id: "borderRepresentativeSector",
    kind: "plainLine",
    mn: "Хилийн төлөөлөгчийн хариуцсан хэсэг",
    desc: "Хилийн төлөөлөгч (бүрэн эрхт)-ийн хариуцсан хэсэг.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
  },
  {
    id: "borderPostJunction",
    kind: "plainLine",
    mn: "Хилийн заставын уулзвар",
    desc: "Хилийн заставуудын хариуцах хэсгийн уулзвар.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
  },
  {
    id: "borderGuardJunction",
    kind: "plainLine",
    mn: "Хилийн харуулын уулзвар",
    desc: "Хилийн харуулуудын хариуцах хэсгийн уулзвар.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
    dashed: true,
  },
  {
    id: "borderDetachmentDepthLine",
    kind: "plainLine",
    mn: "Хилийн отрядын гүний хязгаарлах шугам",
    desc: "Хилийн отрядын гүний хязгаарлах шугам.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
  },
  {
    id: "borderPostDepthLine",
    kind: "plainLine",
    mn: "Хилийн заставын гүний хязгаарлах шугам",
    desc: "Хилийн заставын гүний хязгаарлах шугам.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
    dashed: true,
  },
  {
    id: "borderGuardDepthLine",
    kind: "plainLine",
    mn: "Хилийн харуулын гүний хязгаарлах шугам",
    desc: "Хилийн харуулын гүний хязгаарлах шугам.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
    dashed: true,
  },
  {
    id: "borderStrip",
    kind: "plainLine",
    mn: "Хилийн зурвас",
    desc: "Хилийн зурвас.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
    dashed: true,
  },
  {
    id: "borderScreenLine",
    kind: "plainLine",
    mn: "Хил халхлалтын зааг",
    desc: "Хил халхлалтын зааг.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
  },
  {
    id: "borderMainDefenceLine",
    kind: "plainLine",
    mn: "Хил хамгаалалтын үндсэн зааг",
    desc: "Хил хамгаалалтын үндсэн зааг.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
  },
  {
    id: "borderDepthDefenceLine",
    kind: "plainLine",
    mn: "Хил хамгаалалтын гүний зааг",
    desc: "Хил хамгаалалтын гүний зааг.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
  },
  {
    id: "borderViolationDirection",
    kind: "strikeDirection",
    mn: "Хилийн зөрчил гарч болзошгүй чиглэл",
    desc: "Хилийн зөрчил гарч болзошгүй чиглэл.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
    dashed: true,
  },
  {
    id: "borderSpecialOpSector",
    kind: "area",
    mn: "Хилийн тусгай ажиллагаа явуулах хэсэг",
    desc: "Хилийн тусгай ажиллагаа явуулах хэсэг. Хил залгаа улсын хил хамгаалах байгууллагатай хамтран явуулсан тохиолдолд хилээс цааш ногоон өнгөөр зурна.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
  },
  {
    id: "borderSearchSector",
    kind: "area",
    mn: "Хилийн эрэл явуулах хэсэг",
    desc: "Хилийн эрэл явуулах хэсэг. Хил залгаа улсын хил хамгаалах байгуулагатай хамтран явуулсан тохиолдолд хилээс цааш ногоон өнгөөр зурна.",
    ref: "Т4-2022 §16.1 Хавсралт 17",
  },
];

export function getLineType(id: string): LineTypeDef | undefined {
  return LINE_TYPES.find((t) => t.id === id);
}
