import type { SymbolDef } from "@/types/symbol";

export const CATEGORIES = [
  "Удирдлага, командын байр",
  "Анги, салбар",
  "Салаа, тасаг, нэгж",
  "Төрөл, мэргэжлийн цэрэг",
  "Ажиллагаа",
  "Гал ба цохилт",
  "Хөдөлгөөн",
  "Явган зэвсэг",
  "Тээврийн хэрэгсэл, техник",
  "Агаарын хэрэгсэл",
  "Кибер, холбооны сүлжээ",
  "Хил, дотоод, онцгой байдал",
] as const;

/**
 * A note appended in the UI (see SymbolTooltip) whenever `approximate` is
 * true: the frame shape / echelon / affiliation color are reproduced exactly
 * from Т4-2022, but the manual's hand-drawn pictorial glyph for this entry
 * could not be recovered from the source PDF's text layer, so a short
 * Mongolian abbreviation stands in for it.
 */
export const APPROXIMATION_NOTE =
  "Хүрээ, шатлал, өнгө нь Т4-2022 зааврын дагуу үнэн зөв; дотоод дүрс нь эх сурвалжийн зурган тэмдгийг орлуулсан товчилсон тэмдэглэгээ.";

export const SYMBOLS: SymbolDef[] = [
  // ───────────────────────── Удирдлага, командын байр (§2.1) ─────────────────────────
  {
    id: "zhzsh",
    category: "Удирдлага, командын байр",
    mn: "Зэвсэгт хүчний Жанжин штаб",
    label: "ЗХЖШ",
    frame: "rect",
    color: "friendly",
    desc: "Монгол Улсын Зэвсэгт хүчний Жанжин штабын удирдлагын байр. Ажлын зураг дээр тэгш өнцөгт хүрээтэй, тугийг фронт руу чиглүүлж зурна.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "bk",
    category: "Удирдлага, командын байр",
    mn: "Бүсийн командлал (цэргийн штаб)",
    label: "БК",
    frame: "rect",
    color: "friendly",
    desc: "Бүсийн командлалын удирдлагын байр (ЦШ — цэргийн штаб).",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "hzck",
    category: "Удирдлага, командын байр",
    mn: "Хуурай замын цэргийн командлал",
    label: "ХЗЦК",
    frame: "rect",
    color: "friendly",
    desc: "Хуурай замын цэргийн командлалын удирдлагын байр.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "thck",
    category: "Удирдлага, командын байр",
    mn: "Тусгай хүчний цэргийн командлал",
    label: "ТХЦК",
    frame: "rect",
    color: "friendly",
    desc: "Тусгай хүчний цэргийн командлалын удирдлагын байр.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "ack",
    category: "Удирдлага, командын байр",
    mn: "Агаарын цэргийн командлал",
    label: "АЦК",
    frame: "rect",
    color: "friendly",
    desc: "Агаарын цэргийн командлалын удирдлагын байр.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "hheg",
    category: "Удирдлага, командын байр",
    mn: "Хил хамгаалахын удирдлагын байгууллага",
    label: "ХХЕГ",
    frame: "rect",
    color: "green",
    desc: "Хил хамгаалалтыг удирдах төрийн захиргааны байгууллага.",
    ref: "Т4-2022 §2.1 / §16.1",
  },
  {
    id: "obeg",
    category: "Удирдлага, командын байр",
    mn: "Онцгой байдлын ерөнхий газар",
    label: "ОБЕГ",
    frame: "rect",
    color: "orange",
    desc: "Онцгой байдлын удирдлагын төв байгууллага.",
    ref: "Т4-2022 §2.1 / §16.2",
  },
  {
    id: "dts",
    category: "Удирдлага, командын байр",
    mn: "Дотоодын цэргийн удирдлагын байгууллага",
    label: "ДЦ",
    frame: "rect",
    color: "tan",
    desc: "Дотоодын цэргийн удирдлагын байгууллагын байр.",
    ref: "Т4-2022 §2.1 / §16.3",
  },
  {
    id: "brigadCP",
    category: "Удирдлага, командын байр",
    mn: "Бригадын командын байр",
    label: "ШТАБ",
    frame: "rect",
    color: "friendly",
    echelon: "X",
    desc: "Холимог бүтэцтэй мотобуудлагын бригадын командын байр. Төрөл мэргэжлийн цэргийн таних тэмдгийг төв хэсэгт зурна.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "horooCP",
    category: "Удирдлага, командын байр",
    mn: "Хорооны командын байр",
    label: "ШТАБ",
    frame: "rect",
    color: "friendly",
    echelon: "III",
    desc: "Хорооны командын байр.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "batalonCP",
    category: "Удирдлага, командын байр",
    mn: "Батальон (дивизион)-ы удирдлагын байр",
    label: "ШТАБ",
    frame: "rect",
    color: "friendly",
    echelon: "II",
    desc: "Батальон (артиллерийн дивизион)-ы удирдлагын байр.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "rotCP",
    category: "Удирдлага, командын байр",
    mn: "Ротын захирагчийн хянах байр",
    label: "ХБ",
    frame: "triangle",
    color: "friendly",
    echelon: "I",
    desc: "Хяналт/хангалтын байрыг адил хажуут гурвалжин хүрээгээр дүрсэлнэ. Ахлах даргын таних тэмдгийг зурсан үед ротын таних тэмдгийг дахин зурахгүй.",
    ref: "Т4-2022 §2.1 / §1.3",
  },
  {
    id: "salaaCP",
    category: "Удирдлага, командын байр",
    mn: "Салааны захирагчийн хянах байр",
    label: "ХБ",
    frame: "triangle",
    color: "friendly",
    echelon: "c",
    desc: "Салааны захирагчийн хянах байр.",
    ref: "Т4-2022 §2.1",
  },

  // ───────────────────────── Анги, салбар (§2.2) ─────────────────────────
  {
    id: "brigade",
    category: "Анги, салбар",
    mn: "Бригад (явган цэргийн байлдааны машинтай)",
    label: "БР",
    frame: "rect",
    color: "friendly",
    echelon: "X",
    desc: "Төрөл мэргэжлийн буюу суурилсан зэвсэглэл, цэргийн техникийн таних тэмдгээр ялгана.",
    ref: "Т4-2022 §2.2",
    approximate: true,
  },
  {
    id: "horoo",
    category: "Анги, салбар",
    mn: "Хороо (танкийн)",
    label: "ХОР",
    frame: "rect",
    color: "friendly",
    echelon: "III",
    desc: "Хорооны шатлалын тэмдэг III, тэгш өнцөгт хүрээ.",
    ref: "Т4-2022 §2.2",
    approximate: true,
  },
  {
    id: "batalion",
    category: "Анги, салбар",
    mn: "Батальон (хуягт тээвэрлэгчтэй)",
    label: "БАТ",
    frame: "rect",
    color: "friendly",
    echelon: "II",
    desc: "Батальоны шатлалын тэмдэг II, тэгш өнцөгт хүрээ.",
    ref: "Т4-2022 §2.2",
    approximate: true,
  },
  {
    id: "batalionAuto",
    category: "Анги, салбар",
    mn: "Батальон (автомашинтай)",
    label: "БАТ/А",
    frame: "rect",
    color: "friendly",
    echelon: "II",
    desc: "Автомашинтай батальон.",
    ref: "Т4-2022 §2.2",
    approximate: true,
  },
  {
    id: "rot",
    category: "Анги, салбар",
    mn: "Рот (батарей)",
    label: "РОТ",
    frame: "rect",
    color: "friendly",
    echelon: "I",
    desc: "Ротын (батарейн) шатлалын тэмдэг I, тэгш өнцөгт хүрээ.",
    ref: "Т4-2022 §2.2",
    approximate: true,
  },

  // ───────────────────────── Салаа, тасаг, нэгж (§2.3) ─────────────────────────
  {
    id: "salaa",
    category: "Салаа, тасаг, нэгж",
    mn: "Салаа",
    label: "с",
    frame: "rect",
    color: "friendly",
    echelon: "c",
    desc: "Салааны тэмдэглэгээ — зенит, артиллерийн салааг дугуй хүрээгээр тэмдэглэнэ.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "tasag",
    category: "Салаа, тасаг, нэгж",
    mn: "Тасаг (ЯЦБМ-тай)",
    label: "т",
    frame: "rect",
    color: "friendly",
    echelon: "т",
    desc: "ЯЦБМ-тай тасаг.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "buleg",
    category: "Салаа, тасаг, нэгж",
    mn: "Бүлэг (ЯЦБМ-тай)",
    label: "бү",
    frame: "rect",
    color: "friendly",
    echelon: "бү",
    desc: "ЯЦБМ-тай бүлэг.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "gurval",
    category: "Салаа, тасаг, нэгж",
    mn: "Байлдааны гурвал",
    label: "Δ",
    frame: "circle",
    color: "friendly",
    desc: "БД-1/100-ийн 4 дүгээр зүйлийн 4.3 дахь хэсгийг баримтална. Дугуй дүрсийг үүрэг гүйцэтгэх чиглэлд перпендикуляр байрлуулж зурна.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "hos",
    category: "Салаа, тасаг, нэгж",
    mn: "Байлдааны хос",
    label: "хос",
    frame: "circle",
    color: "friendly",
    desc: "БД-1/100-ийн 4 дүгээр зүйлийн 4.1–4.2.6 дахь заалтыг баримтална.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "tsereg",
    category: "Салаа, тасаг, нэгж",
    mn: "Цэрэг (хүн)",
    label: "",
    frame: "circle",
    color: "friendly",
    desc: "Ганц цэргийн байрлалыг дугуй хүрээгээр тэмдэглэнэ.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "olzlogdson",
    category: "Салаа, тасаг, нэгж",
    mn: "Олзлогдсон болон шархадсан цэрэг",
    label: "⊘",
    frame: "circle",
    color: "friendly",
    desc: "Олзлогдсон болон шархадсан цэргийн байрлал.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "alagdsan",
    category: "Салаа, тасаг, нэгж",
    mn: "Алагдсан цэрэг",
    label: "X",
    frame: "circle",
    color: "friendly",
    desc: "Алагдсан цэргийн байрлал.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "buudagch",
    category: "Салаа, тасаг, нэгж",
    mn: "Буудагч (пулемётчин)",
    label: "БУУ",
    frame: "point",
    color: "friendly",
    desc: "Байлдааны төлөвлөлтөд АКМ, гранатомёт, пулемёт зэрэг нэг бүрийн буудлагын зэвсэглэлийн таних тэмдгээр ялгаж зурна.",
    ref: "Т4-2022 §2.3",
    glyph: `<line x1="6" y1="16" x2="20" y2="16"/><line x1="20" y1="12" x2="20" y2="20"/><line x1="23" y1="12" x2="23" y2="20"/>`,
  },
  {
    id: "yavganerguul",
    category: "Салаа, тасаг, нэгж",
    mn: "Явган эргүүл",
    label: "ЭРГ",
    frame: "point",
    color: "friendly",
    desc: "Явган эргүүлийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    glyph: `<ellipse cx="16" cy="16" rx="9" ry="5" stroke-dasharray="3 2"/><circle cx="16" cy="16" r="1.8" fill="currentColor"/><path d="M25 13 L30 11 M28 9 L30 11 L28 13"/>`,
  },
  {
    id: "nuutsmanaa",
    category: "Салаа, тасаг, нэгж",
    mn: "Нууц манаа",
    label: "НМ",
    frame: "triangle",
    color: "friendly",
    desc: "Нууц манааны байр.",
    ref: "Т4-2022 §2.3",
    glyph: `<path d="M16 8 L24 23 H8 Z"/><circle cx="16" cy="18" r="1.6" fill="currentColor"/>`,
  },
  {
    id: "tagnuulbuleg",
    category: "Салаа, тасаг, нэгж",
    mn: "Тагнуулын бүлэг",
    label: "ТАГ",
    frame: "point",
    color: "friendly",
    desc: "Тагнуулын бүлгийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    glyph: `<path d="M4 16 H14 M9 11 L4 16 L9 21"/><circle cx="21" cy="16" r="5" fill="currentColor"/><line x1="17" y1="20" x2="25" y2="12"/>`,
  },
  {
    id: "dairahotryad",
    category: "Салаа, тасаг, нэгж",
    mn: "Дайрах отряд",
    label: "ДАЙР",
    frame: "point",
    color: "friendly",
    desc: "Дайрах отрядын тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    glyph: `<path d="M4 16 H12 M8 11 L4 16 L8 21"/><rect x="14" y="12" width="8" height="8"/>`,
  },
  {
    id: "tagnuulotryad",
    category: "Салаа, тасаг, нэгж",
    mn: "Тагнуулын отряд",
    label: "Т.ОТР",
    frame: "point",
    color: "friendly",
    desc: "Тагнуулын отрядын тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    glyph: `<path d="M4 16 H12 M8 11 L4 16 L8 21"/><ellipse cx="20" cy="16" rx="7" ry="4.5"/>`,
  },
  {
    id: "tagnuultusgai",
    category: "Салаа, тасаг, нэгж",
    mn: "Тагнуулын тусгай сэргийлэх",
    label: "Т.СЭР",
    frame: "point",
    color: "friendly",
    desc: "Тагнуулын тусгай сэргийлэхийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    glyph: `<path d="M4 16 H12 M8 11 L4 16 L8 21"/><circle cx="20" cy="16" r="5"/>`,
  },
  {
    id: "baildaanytagnuul",
    category: "Салаа, тасаг, нэгж",
    mn: "Байлдааны тагнуулын сэргийлэх",
    label: "Б.ТАГ",
    frame: "point",
    color: "friendly",
    desc: "Байлдааны тагнуулын сэргийлэхийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    glyph: `<path d="M4 16 H12 M8 11 L4 16 L8 21"/><ellipse cx="20" cy="16" rx="7" ry="4.5"/><line x1="20" y1="11.5" x2="20" y2="20.5"/>`,
  },
  {
    id: "officertagnuul",
    category: "Салаа, тасаг, нэгж",
    mn: "Офицерын тагнуулын сэргийлэх",
    label: "ОФ",
    frame: "point",
    color: "friendly",
    desc: "Офицерын тагнуулын сэргийлэхийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    glyph: `<path d="M4 16 H12 M8 11 L4 16 L8 21"/><ellipse cx="20" cy="16" rx="7" ry="4.5"/><text x="20" y="19" font-size="5.5" text-anchor="middle" stroke="none" fill="currentColor">ОФ</text>`,
  },
  {
    id: "sergiylehmashine",
    category: "Салаа, тасаг, нэгж",
    mn: "Сэргийлэхийн машин",
    label: "СЭР.М",
    frame: "point",
    color: "friendly",
    desc: "Сэргийлэхийн машины тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    glyph: `<path d="M4 16 H12 M8 11 L4 16 L8 21"/><ellipse cx="20" cy="16" rx="7" ry="4.5"/><line x1="15" y1="20" x2="25" y2="12"/>`,
  },
  {
    id: "yavgansergiyleh",
    category: "Салаа, тасаг, нэгж",
    mn: "Явган сэргийлэх",
    label: "СЭР",
    frame: "point",
    color: "friendly",
    desc: "Явган сэргийлэхийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    glyph: `<path d="M4 16 H12 M8 11 L4 16 L8 21"/><circle cx="20" cy="16" r="5"/><line x1="16" y1="20" x2="24" y2="12"/>`,
  },

  // ───────────────────────── Төрөл, мэргэжлийн цэрэг (§2.4) ─────────────────────────
  {
    id: "erhtsereg",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Ерөнхий цэрэг",
    label: "ЕР",
    frame: "ellipse",
    color: "black",
    desc: "Тухайн анги, салбар, нэгжийн суурилсан үндсэн цэргийн техник (ЯЦБМ, хуягт тээвэрлэгч, автомашин)-ийн тэмдгийг хэрэглэнэ.",
    ref: "Т4-2022 §2.4",
    glyph: `<path d="M4 6h12l4 3-4 3H4z"/><path d="M4 13h12l4 3-4 3H4z"/><path d="M4 20h12l4 3-4 3H4z"/>`,
  },
  {
    id: "holimogMB",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Холимог мотобуудлагын салбар",
    label: "МБ",
    frame: "ellipse",
    color: "black",
    desc: "ЯЦБМ, хуягт тээвэрлэгч, автомашинтай холимог мотобуудлагын салбар.",
    ref: "Т4-2022 §2.4",
    glyph: `<ellipse cx="16" cy="16" rx="11" ry="7"/>`,
  },
  {
    id: "turgenhuchin",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Түргэн байрлах хүчин",
    label: "ТБХ",
    frame: "point",
    color: "black",
    desc: "Түргэн байрлах хүчний тэмдэг. Шатлалын хүрээг ашиглан нэгжийг тодотгоно.",
    ref: "Т4-2022 §2.4 / Хавсралт 1",
    glyph: `<path d="M16 8 L16 22 M16 12 L9 8 M16 12 L23 8"/>`,
  },
  {
    id: "tusgaitomilolt",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Тусгай томилолтын анги, салбар",
    label: "ТТ",
    frame: "circle",
    color: "black",
    desc: "Тусгай томилолтын анги, салбарын тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 1",
    glyph: `<circle cx="16" cy="16" r="10"/><path d="M16 10 L16 21 M16 14 L11 11 M16 14 L21 11"/>`,
  },
  {
    id: "shuherdesant",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Шүхэр десантын",
    label: "ШД",
    frame: "circle",
    color: "black",
    desc: "Шүхэр десантын батальон/рот/салаа/тасгийн тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 1",
    glyph: `<path d="M6 10 H26 L16 24 Z"/>`,
  },
  {
    id: "uulyn",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Уулын",
    label: "УУЛ",
    frame: "triangle",
    color: "black",
    desc: "Уулын батальоны тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 1",
    glyph: `<path d="M16 6 L26 24 H6 Z" fill="currentColor"/>`,
  },
  {
    id: "tagnuul",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Тагнуул",
    label: "ТАГ",
    frame: "point",
    color: "black",
    desc: "Тагнуулын батальон/ротын ерөнхий тэмдэг.",
    ref: "Т4-2022 §2.4",
    glyph: `<line x1="9" y1="23" x2="23" y2="9"/>`,
  },
  {
    id: "morьttsereg",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Морьт цэрэг",
    label: "МОР",
    frame: "point",
    color: "black",
    desc: "Морьт цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4",
    glyph: `<path d="M16 8 L16 20 M16 12 L9 8 M16 12 L23 8 M12 16 L20 24"/>`,
  },
  {
    id: "tank",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Танк",
    label: "ТАНК",
    frame: "diamond",
    color: "black",
    desc: "Танкийн ерөнхий тэмдэг — ромбо хэлбэрийн хүрээ.",
    ref: "Т4-2022 §2.4 / §2.10",
    glyph: `<path d="M16 6 L26 16 L16 26 L6 16 Z"/>`,
  },
  {
    id: "nisehhuchin",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Нисэх хүчин",
    label: "НХ",
    frame: "point",
    color: "black",
    desc: "Агаарын нисэх хүчний ерөнхий тэмдэг.",
    ref: "Т4-2022 §2.4",
    glyph: `<path d="M16 8 L16 19 M16 12 L9 8 M16 12 L23 8"/><circle cx="16" cy="22" r="2.2"/>`,
  },
  {
    id: "kiber",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Кибер",
    label: "КИБ",
    frame: "point",
    color: "black",
    desc: "Кибер аюулгүй байдлын цэргийн ерөнхий тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 6",
    glyph: `<text x="16" y="23" font-size="21" text-anchor="middle" stroke="none" fill="currentColor" font-family="Georgia, 'Times New Roman', serif">&#931;</text>`,
  },
  {
    id: "artilleryEr",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Артиллерийн ерөнхий тэмдэг",
    label: "АРТ",
    frame: "circle",
    color: "black",
    desc: "Артиллерийн цэргийн ерөнхий тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 3",
    glyph: `<circle cx="16" cy="16" r="6" fill="currentColor"/>`,
  },
  {
    id: "tsadh",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "ЦАДХ",
    label: "ЦАДХ",
    frame: "point",
    color: "black",
    desc: "Цэрэг-агаарын довтолгооноос хамгаалах цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4",
    glyph: `<path d="M16 6 L16 24 M11 11 L16 6 L21 11"/><line x1="11" y1="18" x2="21" y2="18"/><line x1="11" y1="21" x2="21" y2="21"/>`,
  },
  {
    id: "zenitpuujinart",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Зенитийн пуужин – артиллерийн хосолсон",
    label: "ЗПА",
    frame: "point",
    color: "black",
    desc: "Зенитийн пуужин-артиллерийн хосолсон цогцолборын тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 4",
    glyph: `<path d="M16 6 L16 24 M11 11 L16 6 L21 11"/><line x1="11" y1="18" x2="21" y2="18"/><line x1="9" y1="24" x2="23" y2="24"/>`,
  },
  {
    id: "zenitpuujin",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Зенитийн пуужин",
    label: "ЗП",
    frame: "point",
    color: "black",
    desc: "Зенитийн пуужингийн ерөнхий тэмдэг (Т-тактикийн, ОТ-оператив-тактикийн, ОЦ-олон цэнэгт).",
    ref: "Т4-2022 §2.4 / Хавсралт 4",
    glyph: `<path d="M11 24 V14 Q11 6 16 6 Q21 6 21 14 V24 Z"/>`,
  },
  {
    id: "rls",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Радиолокацийн станц (РЛС)",
    label: "РЛС",
    frame: "point",
    color: "black",
    desc: "Радиолокацийн станцын ерөнхий тэмдэглэгээ.",
    ref: "Т4-2022 §2.4",
    glyph: `<path d="M8 22 L16 8 L24 22 Z"/><line x1="6" y1="24" x2="10" y2="20"/><line x1="26" y1="24" x2="22" y2="20"/>`,
  },
  {
    id: "holboo",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Холбоо",
    label: "ХОЛ",
    frame: "point",
    color: "black",
    desc: "Холбооны цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 7",
    glyph: `<path d="M18 6 L10 18 H15 L13 26 L23 13 H17 Z"/>`,
  },
  {
    id: "radiotagnuul",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Радио тагнуулын",
    label: "Р.ТАГ",
    frame: "point",
    color: "black",
    desc: "Радио тагнуулын тэмдэг.",
    ref: "Т4-2022 §2.4",
    glyph: `<path d="M6 22 Q11 14 16 20 Q21 26 26 10"/><path d="M22 8 L27 9 L25 14"/>`,
  },
  {
    id: "medeeleлsetgel",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Мэдээлэл сэтгэл зүйн",
    label: "МСЗ",
    frame: "point",
    color: "black",
    desc: "Мэдээлэл, сэтгэл зүйн хангалтын цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4 / §9",
    glyph: `<path d="M16 12 V26 M9 8 Q9 15 16 15 Q23 15 23 8"/>`,
  },
  {
    id: "tsergiinbairzui",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн байр зүй",
    label: "БЗ",
    frame: "triangle",
    color: "black",
    desc: "Цэргийн байр зүйн алба.",
    ref: "Т4-2022 §2.4",
    glyph: `<path d="M16 8 L24 23 Q16 26 8 23 Z"/>`,
  },
  {
    id: "hemzhilzui",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Хэмжил зүйн",
    label: "ХЭМЖ",
    frame: "rect",
    color: "black",
    desc: "Цэргийн зэвсэглэл, техникийн хэмжил зүйн алба.",
    ref: "Т4-2022 §2.4 / §41.7",
    glyph: `<rect x="6" y="12" width="20" height="8"/><line x1="10" y1="16" x2="22" y2="16"/><circle cx="19" cy="16" r="1.3" fill="currentColor"/>`,
  },
  {
    id: "orionZaiTandalt",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Орон зайн тандалт судалгаа",
    label: "ОЗТ",
    frame: "point",
    color: "black",
    desc: "Орон зайн тандалт судалгааны алба.",
    ref: "Т4-2022 §2.4",
    glyph: `<path d="M20 8 Q10 8 10 18 L10 24 M10 24 L7 21 M10 24 L13 21"/><circle cx="21" cy="7" r="1.5" fill="currentColor"/>`,
  },
  {
    id: "tsaguur",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цаг уур",
    label: "ЦУ",
    frame: "point",
    color: "black",
    desc: "Цаг уурын хангалтын алба.",
    ref: "Т4-2022 §2.4 / §40.10",
    glyph: `<line x1="8" y1="10" x2="8" y2="18"/><path d="M8 14 H24 M20 10 L24 14 L20 18"/>`,
  },
  {
    id: "chb",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цацраг, хими, биологиос хамгаалахын",
    label: "ЦХБ",
    frame: "point",
    color: "black",
    desc: "Цацраг, хими, биологиос хамгаалах цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 5",
    glyph: `<circle cx="11" cy="14" r="4"/><circle cx="21" cy="14" r="4"/><circle cx="16" cy="20" r="1.5" fill="currentColor"/>`,
  },
  {
    id: "tsergiinInj",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн инженер",
    label: "ИНЖ",
    frame: "rect",
    color: "black",
    desc: "Инженерийн цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 6",
    glyph: `<path d="M8 24 V10 H24 V24"/>`,
  },
  {
    id: "guuruus",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Гүүр ус гатлалтын анги, салбар",
    label: "ГҮҮР",
    frame: "point",
    color: "black",
    desc: "Гүүр, ус гатлалтын анги, салбарын тэмдэг.",
    ref: "Т4-2022 §2.4",
    glyph: `<path d="M4 13 Q8 9 12 13 T20 13 T28 13"/><path d="M4 19 Q8 15 12 19 T20 19 T28 19"/>`,
  },
  {
    id: "barilga",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Барилгын анги, салбар",
    label: "БАР",
    frame: "circle",
    color: "black",
    desc: "Барилга, инженерийн цэргийн анги, салбар.",
    ref: "Т4-2022 §2.4 / Хавсралт 11",
    glyph: `<path d="M6 24 V14 L16 6 L26 14 V24 Z"/>`,
  },
  {
    id: "materialhang",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Материалын хангалт",
    label: "МАТ",
    frame: "rect",
    color: "black",
    desc: "Материалын хангалтын алба.",
    ref: "Т4-2022 §2.4 / Хавсралт 10",
    glyph: `<path d="M9 8 V20 Q9 24 13 24 H22"/>`,
  },
  {
    id: "tsergiinzevsэglэl",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн зэвсэглэл",
    label: "ЗЭВ",
    frame: "point",
    color: "black",
    desc: "Цэргийн зэвсэглэлийн хангалтын алба.",
    ref: "Т4-2022 §2.4 / Хавсралт 11",
    glyph: `<circle cx="16" cy="13" r="5"/><circle cx="16" cy="13" r="1.3" fill="currentColor"/><line x1="16" y1="18" x2="16" y2="24"/>`,
  },
  {
    id: "tsergiintehnik",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн техникийн",
    label: "ТЕХ",
    frame: "point",
    color: "black",
    desc: "Цэргийн техникийн хангалтын алба.",
    ref: "Т4-2022 §2.4 / Хавсралт 12",
    glyph: `<path d="M8 12 L14 16 L8 20 Z M24 12 L18 16 L24 20 Z"/><line x1="14" y1="16" x2="18" y2="16"/>`,
  },
  {
    id: "tsergiinhunemn",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн хүн эмнэлэг",
    label: "ЭМ",
    frame: "point",
    color: "black",
    desc: "Цэргийн эрүүл мэндийн хангалтын алба.",
    ref: "Т4-2022 §2.4 / Хавсралт 14",
    glyph: `<line x1="16" y1="9" x2="16" y2="23"/><line x1="9" y1="16" x2="23" y2="16"/>`,
  },
  {
    id: "tsergiintsagdaa",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн цагдаа",
    label: "MP",
    frame: "rect",
    color: "tan",
    desc: "Цэргийн цагдаагийн алба (MP — Military Police).",
    ref: "Т4-2022 §2.4",
  },
  {
    id: "oronNutgiinTs",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Орон нутгийн цэрэг",
    label: "ОН",
    frame: "rect",
    color: "brown",
    desc: "Орон нутгийн цэргийн тэмдэг — хүрэн өнгөөр тэмдэглэнэ.",
    ref: "Т4-2022 §2.4 / §1.7.10",
  },
  {
    id: "holimogTbu",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Холимог бүрэлдэхүүнтэй тактикийн бүлэг",
    label: "ТБҮ",
    frame: "circle",
    color: "black",
    desc: "Мото, механик, морьт, орон нутгийн цэрэг гэх мэт холимог бүрэлдэхүүнтэй тактикийн бүлэг.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },

  // ───────────────────────── Ажиллагаа (§2.5) ─────────────────────────
  {
    id: "otolt",
    category: "Ажиллагаа",
    mn: "Отолт",
    label: "ОТОЛТ",
    frame: "arrow",
    color: "friendly",
    desc: "Дайсны амьд хэл, баримт бичиг, зэвсэглэл, техникийг олзлох зорилгоор жижиг хүчээр гэнэт хийх богино хугацааны ажиллагаа.",
    ref: "Т4-2022 §2.5",
    glyph: `<path d="M6 16 L26 16 M20 10 L26 16 L20 22"/><path d="M6 10 Q10 16 6 22"/>`,
  },
  {
    id: "haiguul",
    category: "Ажиллагаа",
    mn: "Хайгуул",
    label: "ХАЙГУУЛ",
    frame: "arrow",
    color: "friendly",
    desc: "Хайгуул хийж буй салбарын ажиллагааны чиглэл.",
    ref: "Т4-2022 §2.5",
    glyph: `<path d="M22 16 H8 M13 10 L8 16 L13 22"/><path d="M22 10 A6 6 0 1 1 22 22"/>`,
  },
  {
    id: "merdenhoolt",
    category: "Ажиллагаа",
    mn: "Мөрдөн хөөлт",
    label: "МХ",
    frame: "arrow",
    color: "friendly",
    desc: "Ухарч байгаа дайсныг мөрдөн хөөх ажиллагаа.",
    ref: "Т4-2022 §2.5 / §19.1",
    glyph: `<path d="M14 11 L9 16 L14 21"/><line x1="14" y1="16" x2="18" y2="16" stroke-dasharray="2 2"/><path d="M27 11 L22 16 L27 21"/><line x1="18" y1="16" x2="22" y2="16"/>`,
  },
  {
    id: "buslэh",
    category: "Ажиллагаа",
    mn: "Бүслэх",
    label: "БҮСЛЭХ",
    frame: "arrow",
    color: "friendly",
    desc: "Дайсны бүлэглэлийг тодорхой чиглэлд бүслэн тусгаарлах ажиллагаа.",
    ref: "Т4-2022 §2.5 / §23",
    glyph: `<path d="M23 9 A10 10 0 1 0 25 16"/><path d="M25 16 L28 12 M25 16 L21 14"/>`,
  },
  {
    id: "buslenustgah",
    category: "Ажиллагаа",
    mn: "Бүслэн устгах",
    label: "Б.УСТГАХ",
    frame: "arrow",
    color: "friendly",
    desc: "Бүслэгдсэн дайсны бүлэглэлийг устгах ажиллагаа.",
    ref: "Т4-2022 §2.5 / §23",
    glyph: `<circle cx="16" cy="16" r="10"/><path d="M10 10 L22 22 M22 10 L10 22"/>`,
  },
  {
    id: "orooh",
    category: "Ажиллагаа",
    mn: "Ороох",
    label: "ОРООХ",
    frame: "arrow",
    color: "friendly",
    desc: "Хүч хэрэгслийн ороох маневр.",
    ref: "Т4-2022 §2.5 / §1.2.3",
    glyph: `<rect x="11" y="13" width="7" height="6"/><path d="M25 16 A10 10 0 1 1 20 8"/><path d="M20 8 L24 7 M20 8 L21 11"/>`,
  },
  {
    id: "toiroh",
    category: "Ажиллагаа",
    mn: "Тойрох",
    label: "ТОЙРОХ",
    frame: "arrow",
    color: "friendly",
    desc: "Хүч хэрэгслийн тойрох маневр.",
    ref: "Т4-2022 §2.5 / §1.2.3",
    glyph: `<rect x="12" y="13" width="7" height="6"/><path d="M20 9 A9 9 0 1 0 21 23"/><path d="M21 23 L24 20 M21 23 L18 25"/>`,
  },
  {
    id: "tuiveeh",
    category: "Ажиллагаа",
    mn: "Түйвээх",
    label: "ТҮЙВЭЭХ",
    frame: "arrow",
    color: "friendly",
    desc: "Дайсны байрлалын район, байлдааны журам дотор явуулах түйвээх ажиллагаа.",
    ref: "Т4-2022 §14",
    glyph: `<path d="M4 10 L18 15 M4 10 L9 10 M4 10 L6 13"/><path d="M4 22 L18 17 M4 22 L9 22 M4 22 L6 19"/><path d="M18 8 Q26 16 18 24"/>`,
  },
  {
    id: "tulgarah",
    category: "Ажиллагаа",
    mn: "Тулгарах",
    label: "ТУЛГАРАХ",
    frame: "arrow",
    color: "friendly",
    desc: "Талууд байлдааны үүргээ давшилтаар шийдвэрлэхийг эрмэлзсэн үед үүсэх тулгарах байлдаан.",
    ref: "Т4-2022 §25",
    glyph: `<line x1="4" y1="12" x2="14" y2="12"/><line x1="18" y1="12" x2="28" y2="12"/><line x1="4" y1="20" x2="14" y2="20"/><line x1="18" y1="20" x2="28" y2="20"/><line x1="16" y1="8" x2="16" y2="24"/>`,
  },
  {
    id: "dairalt",
    category: "Ажиллагаа",
    mn: "Дайралт",
    label: "ДАЙРАЛТ",
    frame: "arrow",
    color: "friendly",
    desc: "Хот, суурин дахь байлдаан, бэхлэгдсэн район, бааз руу давших үеийн дайралт.",
    ref: "Т4-2022 §21.12",
    glyph: `<path d="M8 16 H24 M13 11 L8 16 L13 21"/><line x1="24" y1="11" x2="24" y2="21"/>`,
  },

  // ───────────────────────── Гал ба цохилт (§2.6) ─────────────────────────
  {
    id: "galynsector",
    category: "Гал ба цохилт",
    mn: "Галын үндсэн сектор",
    label: "ГАЛ",
    frame: "arrow",
    color: "black",
    desc: "Галын хэрэгслийн үндсэн сектор.",
    ref: "Т4-2022 §2.6",
    glyph: `<circle cx="6" cy="16" r="2" fill="currentColor"/><path d="M8 16 H24 M19 11 L24 16 L19 21"/>`,
  },
  {
    id: "hyralduulsangal",
    category: "Гал ба цохилт",
    mn: "Хуралдуулсан галын зааг",
    label: "ХГ",
    frame: "arrow",
    color: "black",
    desc: "Хуралдуулсан галын зааг.",
    ref: "Т4-2022 §2.6",
    glyph: `<line x1="4" y1="16" x2="28" y2="16"/><line x1="12" y1="12" x2="12" y2="20"/><line x1="20" y1="12" x2="20" y2="20"/>`,
  },
  {
    id: "hodolgoongui_haalt",
    category: "Гал ба цохилт",
    mn: "Хөдөлгөөнгүй хаалт гал",
    label: "ХГГ",
    frame: "arrow",
    color: "black",
    desc: "Хөдөлгөөнгүй дан хаалт гал.",
    ref: "Т4-2022 §2.6",
    glyph: `<line x1="16" y1="8" x2="16" y2="24"/><line x1="10" y1="8" x2="22" y2="8"/><line x1="10" y1="24" x2="22" y2="24"/>`,
  },
  {
    id: "daraalanhyral",
    category: "Гал ба цохилт",
    mn: "Дараалан хуралдуулсан гал",
    label: "ДХГ",
    frame: "arrow",
    color: "black",
    desc: "Дараалан хуралдуулсан гал.",
    ref: "Т4-2022 §2.6",
    glyph: `<line x1="16" y1="6" x2="16" y2="26"/><line x1="12" y1="6" x2="20" y2="6"/><rect x="13" y="10" width="6" height="4"/><rect x="13" y="16" width="6" height="4"/><line x1="12" y1="26" x2="20" y2="26"/>`,
  },
  {
    id: "nisehongots_str",
    category: "Гал ба цохилт",
    mn: "Нисэх онгоцны цохилт",
    label: "ОНГОЦ",
    frame: "arrow",
    color: "friendly",
    desc: "Онгоцны төрөл, огноо, цаг минутыг тэмдэглэнэ.",
    ref: "Т4-2022 §2.6",
    glyph: `<path d="M16 4 L16 24 M16 4 L13 8 M16 4 L19 8"/><path d="M16 15 C8 9 4 11 4 15 C4 19 8 21 16 16"/><path d="M16 15 C24 9 28 11 28 15 C28 19 24 21 16 16"/>`,
  },
  {
    id: "nisdegtereg_str",
    category: "Гал ба цохилт",
    mn: "Нисдэг тэрэгний цохилт",
    label: "Н.ТЭРЭГ",
    frame: "arrow",
    color: "friendly",
    desc: "Нисдэг тэрэгний төрөл, огноо, цаг минутыг тэмдэглэнэ.",
    ref: "Т4-2022 §2.6",
    glyph: `<path d="M16 4 L16 22"/><path d="M16 4 L13 8 M16 4 L19 8"/><path d="M4 15 L14 10 V20 Z"/><path d="M28 15 L18 10 V20 Z"/>`,
  },
  {
    id: "puujin_str",
    category: "Гал ба цохилт",
    mn: "Пуужингийн цохилт",
    label: "ПУУЖИН",
    frame: "circle",
    color: "friendly",
    desc: "Пуужингийн цохилтын тэмдэглэгээ.",
    ref: "Т4-2022 §2.6",
    glyph: `<circle cx="16" cy="16" r="8"/><circle cx="16" cy="16" r="3" fill="currentColor"/>`,
  },
  {
    id: "tsomiin_str",
    category: "Гал ба цохилт",
    mn: "Цөмийн цохилт",
    label: "ЦӨМ",
    frame: "circle",
    color: "friendly",
    desc: "Цөмийн цохилтын тэмдэглэгээ.",
    ref: "Т4-2022 §2.6",
    glyph: `<circle cx="16" cy="16" r="8"/><circle cx="16" cy="16" r="2.5" fill="currentColor"/>`,
  },
  {
    id: "tsomiinEsrэg",
    category: "Гал ба цохилт",
    mn: "Эсрэг талын цөмийн цохилт хийж болзошгүй цэг",
    label: "ЦӨМ?",
    frame: "circle",
    color: "hostile",
    desc: "Эсрэг талын цөмийн цохилт хийж болзошгүй гэж тооцоолсон цэг.",
    ref: "Т4-2022 §2.6",
    glyph: `<circle cx="16" cy="16" r="8"/><circle cx="16" cy="16" r="2.5" fill="currentColor"/>`,
  },

  // ───────────────────────── Хөдөлгөөн (§2.7) ─────────────────────────
  {
    id: "udirdlagynBairynHodolgoon",
    category: "Хөдөлгөөн",
    mn: "Удирдлагын байрын хөдөлгөөн (аяны журманд)",
    label: "УБ",
    frame: "arrow",
    color: "friendly",
    desc: "Удирдлагын байрын аяны журмын хөдөлгөөн.",
    ref: "Т4-2022 §2.7",
    glyph: `<rect x="14" y="6" width="8" height="5"/><path d="M14 6 V16"/><path d="M14 16 H4 M9 12 L4 16 L9 20"/>`,
  },
  {
    id: "horoonyDavshilt",
    category: "Хөдөлгөөн",
    mn: "Хорооны давшилт",
    label: "→",
    frame: "arrow",
    color: "friendly",
    echelon: "III",
    desc: "Хорооны давшилтын чиглэл.",
    ref: "Т4-2022 §2.7",
    glyph: `<path d="M26 16 H6 M12 10 L6 16 L12 22"/>`,
  },
  {
    id: "batalonyDavshilt",
    category: "Хөдөлгөөн",
    mn: "Батальоны давшилт",
    label: "→",
    frame: "arrow",
    color: "friendly",
    echelon: "II",
    desc: "Батальоны давшилтын чиглэл.",
    ref: "Т4-2022 §2.7",
    glyph: `<path d="M26 16 H6 M12 10 L6 16 L12 22"/>`,
  },
  {
    id: "rotynDavshilt",
    category: "Хөдөлгөөн",
    mn: "Ротын давшилт",
    label: "→",
    frame: "arrow",
    color: "friendly",
    echelon: "I",
    desc: "Ротын давшилтын чиглэл.",
    ref: "Т4-2022 §2.7",
    glyph: `<path d="M26 16 H6 M12 10 L6 16 L12 22"/>`,
  },
  {
    id: "tomorzam",
    category: "Хөдөлгөөн",
    mn: "Цэргийг төмөр замаар тээвэрлэх",
    label: "Т/З",
    frame: "point",
    color: "black",
    desc: "Цэргийг төмөр замаар тээвэрлэх тэмдэглэгээ.",
    ref: "Т4-2022 §2.7",
    glyph: `<line x1="6" y1="13" x2="26" y2="13"/><circle cx="10" cy="17" r="2"/><circle cx="14" cy="17" r="2"/><circle cx="20" cy="17" r="2"/><circle cx="24" cy="17" r="2"/>`,
  },
  {
    id: "agaaraar",
    category: "Хөдөлгөөн",
    mn: "Цэргийг агаараар тээвэрлэх",
    label: "АГААР",
    frame: "point",
    color: "friendly",
    desc: "Цэргийг агаараар тээвэрлэх тэмдэглэгээ.",
    ref: "Т4-2022 §2.7",
    glyph: `<line x1="16" y1="10" x2="16" y2="24"/><path d="M16 10 L11 6 M16 10 L21 6 M16 14 L11 12 M16 14 L21 12"/><circle cx="16" cy="26" r="2.2" fill="currentColor"/>`,
  },

  // ───────────────────────── Явган зэвсэг (§2.10 Хүснэгт 13) ─────────────────────────
  {
    id: "avtomat",
    category: "Явган зэвсэг",
    mn: "Автомат, винтов",
    label: "АК",
    frame: "point",
    color: "black",
    desc: "Автомат буу/винтовын тэмдэг.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    glyph: `<line x1="5" y1="16" x2="27" y2="16"/><line x1="11" y1="11" x2="11" y2="21"/>`,
  },
  {
    id: "granatAvtomat",
    category: "Явган зэвсэг",
    mn: "Гранат шидэгчтэй автомат",
    label: "АК+Г",
    frame: "point",
    color: "black",
    desc: "Гранат шидэгч бүхий автомат.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    glyph: `<line x1="5" y1="16" x2="27" y2="16"/><line x1="11" y1="11" x2="11" y2="21"/><line x1="11" y1="21" x2="15" y2="21"/>`,
  },
  {
    id: "avtomatGranatomyot",
    category: "Явган зэвсэг",
    mn: "Автомат гранат шидэгч",
    label: "АГС",
    frame: "point",
    color: "black",
    desc: "Автомат гранат шидэгч (АГС).",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    glyph: `<line x1="5" y1="16" x2="24" y2="16"/><line x1="11" y1="11" x2="11" y2="21"/><path d="M24 16 L29 11"/><text x="25" y="24" font-size="7" stroke="none" fill="currentColor">A</text>`,
  },
  {
    id: "hagasAvtomatGranatomyot",
    category: "Явган зэвсэг",
    mn: "Хагас автомат гранат шидэгч",
    label: "ХАГС",
    frame: "point",
    color: "black",
    desc: "Хагас автомат гранат шидэгч.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    glyph: `<line x1="5" y1="16" x2="24" y2="16"/><line x1="11" y1="11" x2="11" y2="21"/><path d="M24 16 L29 11"/><text x="25" y="24" font-size="7" stroke="none" fill="currentColor">X</text>`,
  },
  {
    id: "mergenBuudagch",
    category: "Явган зэвсэг",
    mn: "Мэргэн буудагчийн винтов",
    label: "СВД",
    frame: "point",
    color: "black",
    desc: "Мэргэн буудагчийн винтов.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    glyph: `<line x1="8" y1="14" x2="22" y2="14"/><line x1="10" y1="19" x2="14" y2="19"/><line x1="18" y1="19" x2="22" y2="19"/>`,
  },
  {
    id: "tasgiinPulemyot",
    category: "Явган зэвсэг",
    mn: "Тасгийн пулемёт",
    label: "РПК",
    frame: "point",
    color: "black",
    desc: "Тасгийн пулемёт.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    glyph: `<line x1="5" y1="16" x2="22" y2="16"/><path d="M22 11 L28 16 L22 21"/>`,
  },
  {
    id: "rotynPulemyot",
    category: "Явган зэвсэг",
    mn: "Ротын пулемёт",
    label: "ПК",
    frame: "point",
    color: "black",
    desc: "Ротын пулемёт.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    glyph: `<line x1="4" y1="16" x2="19" y2="16"/><line x1="10" y1="11" x2="10" y2="21"/><path d="M19 11 L25 16 L19 21"/>`,
  },
  {
    id: "garGranatomyot",
    category: "Явган зэвсэг",
    mn: "Гар гранатомёт",
    label: "РПГ",
    frame: "point",
    color: "black",
    desc: "Гар гранатомёт.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    glyph: `<line x1="4" y1="16" x2="18" y2="16"/><line x1="9" y1="12" x2="9" y2="20"/><path d="M18 12 L24 16 L18 20"/>`,
  },
  {
    id: "suuurtGranatomyot",
    category: "Явган зэвсэг",
    mn: "Суурьт гранатомёт",
    label: "СПГ",
    frame: "point",
    color: "black",
    desc: "Суурьт гранатомёт.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    glyph: `<line x1="3" y1="16" x2="17" y2="16"/><line x1="7" y1="12" x2="7" y2="20"/><line x1="10" y1="12" x2="10" y2="20"/><path d="M17 12 L23 16 L17 20"/>`,
  },
  {
    id: "avtomatGranatomyot2",
    category: "Явган зэвсэг",
    mn: "Автомат гранатомёт",
    label: "АГС-17",
    frame: "point",
    color: "black",
    desc: "Автомат гранатомёт (жишээ нь АГС-17).",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    glyph: `<line x1="2" y1="16" x2="16" y2="16"/><line x1="5" y1="12" x2="5" y2="20"/><line x1="8" y1="12" x2="8" y2="20"/><line x1="11" y1="12" x2="11" y2="20"/><path d="M16 12 L22 16 L16 20"/>`,
  },

  // ───────────────────────── Тээврийн хэрэгсэл, техник (§2.10 Хүснэгт 14–15) ─────────────────────────
  {
    id: "tankAT",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "85мм хүртэлх калибрын танк эсэргүүцэх буу",
    label: "ТЭБ-85",
    frame: "point",
    color: "black",
    desc: "85мм хүртэлх калибрын танк эсэргүүцэх буу.",
    ref: "Т4-2022 §2.10 Хүснэгт 14",
    glyph: `<line x1="4" y1="13" x2="19" y2="13"/><line x1="4" y1="16" x2="19" y2="16"/><line x1="4" y1="19" x2="19" y2="19"/><path d="M19 10 L26 16 L19 22"/>`,
  },
  {
    id: "tankAT2",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "100мм хүртэлх калибрын танк эсэргүүцэх их буу",
    label: "ТЭБ-100",
    frame: "point",
    color: "black",
    desc: "100мм хүртэлх калибрын танк эсэргүүцэх их буу.",
    ref: "Т4-2022 §2.10 Хүснэгт 14",
    glyph: `<line x1="3" y1="13" x2="18" y2="13"/><line x1="3" y1="16" x2="18" y2="16"/><line x1="3" y1="19" x2="18" y2="19"/><path d="M18 10 L25 16 L18 22"/><line x1="21" y1="12" x2="21" y2="20"/>`,
  },
  {
    id: "tankATzaluurt",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Танк эсэргүүцэх залуурт пуужин",
    label: "ТЭЗП",
    frame: "point",
    color: "black",
    desc: "Танк эсэргүүцэх залуурт пуужин.",
    ref: "Т4-2022 §2.10 Хүснэгт 14",
    glyph: `<line x1="3" y1="16" x2="7" y2="16"/><rect x="7" y="12" width="10" height="8"/><path d="M17 12 L24 16 L17 20"/>`,
  },
  {
    id: "yatsBM",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Явган цэргийн байлдааны машин (ЯЦБМ)",
    label: "ЯЦБМ",
    frame: "rect",
    color: "friendly",
    desc: "Явган цэргийн байлдааны машин.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<path d="M5 10 H20 L27 16 L20 22 H5 Z"/><line x1="20" y1="10" x2="20" y2="22"/>`,
  },
  {
    id: "huyagtTeeverlegch",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Хуягт тээвэрлэгч",
    label: "ХТ",
    frame: "rect",
    color: "friendly",
    desc: "Хуягт тээвэрлэгч.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<path d="M5 10 H20 L27 16 L20 22 H5 Z"/>`,
  },
  {
    id: "tankIcon",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Танк",
    label: "ТАНК",
    frame: "diamond",
    color: "friendly",
    desc: "Танкийн ерөнхий тэмдэг.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<path d="M16 5 L27 16 L16 27 L5 16 Z"/>`,
  },
  {
    id: "tankZahiragch",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Танк (захирагчийн)",
    label: "ТАНК-З",
    frame: "diamond",
    color: "friendly",
    desc: "Захирагчийн танк.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<path d="M16 5 L27 16 L16 27 L5 16 Z"/><text x="16" y="20" font-size="9" text-anchor="middle" stroke="none" fill="currentColor">3</text>`,
  },
  {
    id: "hovogchTank",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Хөвөгч танк",
    label: "ТАНК-Х",
    frame: "diamond",
    color: "friendly",
    desc: "Хөвөгч танк.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<path d="M16 5 L27 16 L16 27 L5 16 Z"/><line x1="27" y1="16" x2="31" y2="16"/><line x1="31" y1="13" x2="31" y2="19"/>`,
  },
  {
    id: "ognyometTank",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Огнёмёттой танк",
    label: "ТАНК-О",
    frame: "diamond",
    color: "friendly",
    desc: "Огнёмёттой танк.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<path d="M16 5 L27 16 L16 27 L5 16 Z"/><path d="M16 5 V1 Q19 1 19 4"/>`,
  },
  {
    id: "minTrallTank",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Минийн тралл зүүсэн танк",
    label: "ТАНК-МТ",
    frame: "diamond",
    color: "friendly",
    desc: "Минийн тралл зүүсэн танк.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<path d="M16 5 L27 16 L16 27 L5 16 Z"/><path d="M5 16 H1 M1 12 V20"/>`,
  },
  {
    id: "buldozerTank",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Бульдозертой танк",
    label: "ТАНК-Б",
    frame: "diamond",
    color: "friendly",
    desc: "Бульдозертой танк.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<path d="M16 5 L27 16 L16 27 L5 16 Z"/><path d="M5 16 H1 M1 11 V21 M1 11 H4"/>`,
  },
  {
    id: "avtomashin",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Автомашин",
    label: "АВТО",
    frame: "rect",
    color: "black",
    desc: "Автомашин.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<rect x="5" y="9" width="22" height="14" rx="7"/>`,
  },
  {
    id: "huyaglasanAvto",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Хуягласан автомашин",
    label: "АВТО-Х",
    frame: "rect",
    color: "black",
    desc: "Хуягласан автомашин.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<rect x="5" y="9" width="22" height="14" rx="7"/><line x1="21" y1="9" x2="21" y2="23"/>`,
  },
  {
    id: "mototsikл",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Мотоцикл",
    label: "МЦ",
    frame: "point",
    color: "black",
    desc: "Мотоцикл.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<line x1="8" y1="13" x2="24" y2="13"/><line x1="16" y1="13" x2="16" y2="19"/><circle cx="16" cy="23" r="4"/>`,
  },
  {
    id: "gemtelteiTehnik",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Гэмтэлтэй техник",
    label: "ГЭМТ",
    frame: "diamond",
    color: "hostile",
    desc: "Гэмтэлтэй/эвдэрсэн техник — улаан өнгөөр олзолсон техникийг тэмдэглэнэ.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<path d="M16 5 L27 16 L16 27 L5 16 Z"/><line x1="11" y1="11" x2="21" y2="21"/><line x1="21" y1="11" x2="11" y2="21"/>`,
  },
  {
    id: "sergeenBosgohBoлomжgui",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Сэргээн босгох боломжгүй техник",
    label: "Х",
    frame: "diamond",
    color: "hostile",
    desc: "Сэргээн босгох боломжгүй техник.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    glyph: `<path d="M16 5 L27 16 L16 27 L5 16 Z" fill="currentColor" fill-opacity="0.25"/><line x1="10" y1="10" x2="22" y2="22"/><line x1="22" y1="10" x2="10" y2="22"/>`,
  },

  // ───────────────────────── Агаарын хэрэгсэл (§2.10 Хүснэгт 16) ─────────────────────────
  {
    id: "dairagchOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Дайрагч онгоц",
    label: "ДАЙР",
    frame: "point",
    color: "friendly",
    desc: "Дайрагч онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<path d="M16 4 L16 27 M16 4 L13 8 M16 4 L19 8"/><path d="M16 16 C8 10 4 12 4 16 C4 20 8 22 16 17"/><path d="M16 16 C24 10 28 12 28 16 C28 20 24 22 16 17"/>`,
  },
  {
    id: "sonyogchOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Сөнөөгч онгоц",
    label: "СӨН",
    frame: "point",
    color: "friendly",
    desc: "Сөнөөгч онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<path d="M16 4 L16 27 M16 4 L13 8 M16 4 L19 8"/><path d="M16 16 C8 10 4 12 4 16 C4 20 8 22 16 17"/><path d="M16 16 C24 10 28 12 28 16 C28 20 24 22 16 17"/><line x1="16" y1="22" x2="16" y2="26"/>`,
  },
  {
    id: "bombogdogchOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Бөмбөгдөгч онгоц",
    label: "БӨМБ",
    frame: "point",
    color: "friendly",
    desc: "Бөмбөгдөгч онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<path d="M16 4 L16 24 M16 4 L13 8 M16 4 L19 8"/><path d="M16 15 C8 9 4 11 4 15 C4 19 8 21 16 16"/><path d="M16 15 C24 9 28 11 28 15 C28 19 24 21 16 16"/><circle cx="16" cy="26" r="2.4" fill="currentColor"/>`,
  },
  {
    id: "tagnuulynOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Тагнуулын онгоц",
    label: "Т.ОНГ",
    frame: "point",
    color: "friendly",
    desc: "Тагнуулын онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<path d="M16 4 L16 27 M16 4 L13 8 M16 4 L19 8"/><path d="M16 16 C8 10 4 12 4 16 C4 20 8 22 16 17"/><path d="M16 16 C24 10 28 12 28 16 C28 20 24 22 16 17"/><line x1="16" y1="24" x2="12" y2="26"/>`,
  },
  {
    id: "teevrinOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Тээврийн онгоц",
    label: "Т/О",
    frame: "point",
    color: "friendly",
    desc: "Тээврийн онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<path d="M16 4 L16 22 M16 4 L13 8 M16 4 L19 8"/><path d="M16 14 C8 8 4 10 4 14 C4 18 8 20 16 15"/><path d="M16 14 C24 8 28 10 28 14 C28 18 24 20 16 15"/><circle cx="16" cy="24" r="3.2"/>`,
  },
  {
    id: "rtsOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Радио цахим тэмцлийн онгоц",
    label: "РЦТ",
    frame: "point",
    color: "friendly",
    desc: "Радио цахим тэмцлийн онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<path d="M16 6 L16 27 M16 6 L11 10 M16 6 L21 10 M16 6 L8 8 M16 6 L24 8"/><path d="M16 17 C8 11 4 13 4 17 C4 21 8 23 16 18"/><path d="M16 17 C24 11 28 13 28 17 C28 21 24 23 16 18"/>`,
  },
  {
    id: "irgeniinOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Иргэний онгоц",
    label: "ИРГ",
    frame: "point",
    color: "black",
    desc: "Иргэний онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<line x1="16" y1="9" x2="16" y2="23"/><path d="M16 16 C8 10 4 12 4 16 C4 20 8 22 16 17"/><path d="M16 16 C24 10 28 12 28 16 C28 20 24 22 16 17"/>`,
  },
  {
    id: "baildaanyNisdegTereg",
    category: "Агаарын хэрэгсэл",
    mn: "Байлдааны нисдэг тэрэг",
    label: "Н/Т",
    frame: "point",
    color: "friendly",
    desc: "Байлдааны нисдэг тэрэг.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<path d="M16 4 L16 24"/><path d="M16 4 L13 8 M16 4 L19 8"/><path d="M4 16 L14 11 V21 Z"/><path d="M28 16 L18 11 V21 Z"/><line x1="10" y1="24" x2="22" y2="24"/>`,
  },
  {
    id: "tagnuulynNisdegTereg",
    category: "Агаарын хэрэгсэл",
    mn: "Тагнуулын нисдэг тэрэг",
    label: "Т.Н/Т",
    frame: "point",
    color: "friendly",
    desc: "Тагнуулын нисдэг тэрэг.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<path d="M16 4 L16 24"/><path d="M16 4 L13 8 M16 4 L19 8"/><path d="M4 16 L14 11 V21 Z"/><path d="M28 16 L18 11 V21 Z"/><line x1="16" y1="24" x2="12" y2="27"/>`,
  },
  {
    id: "teevriinNisdegTereg",
    category: "Агаарын хэрэгсэл",
    mn: "Тээврийн нисдэг тэрэг",
    label: "Тр.Н/Т",
    frame: "point",
    color: "friendly",
    desc: "Тээврийн нисдэг тэрэг.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<path d="M16 4 L16 20"/><path d="M16 4 L13 8 M16 4 L19 8"/><path d="M4 15 L14 10 V20 Z"/><path d="M28 15 L18 10 V20 Z"/><circle cx="16" cy="24" r="3.2"/>`,
  },
  {
    id: "nisgegchgui",
    category: "Агаарын хэрэгсэл",
    mn: "Нисгэгчгүй нисэх хэрэгсэл",
    label: "НГ",
    frame: "point",
    color: "black",
    desc: "Нисгэгчгүй нисэх хэрэгсэл (дрон).",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<line x1="9" y1="12" x2="9" y2="20"/><line x1="23" y1="12" x2="23" y2="20"/><line x1="9" y1="16" x2="23" y2="16"/><line x1="16" y1="16" x2="16" y2="22"/>`,
  },
  {
    id: "tagnuulynNisgegchgui",
    category: "Агаарын хэрэгсэл",
    mn: "Тагнуулын нисгэгчгүй нисэх хэрэгсэл",
    label: "Т.НГ",
    frame: "point",
    color: "black",
    desc: "Тагнуулын нисгэгчгүй нисэх хэрэгсэл.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    glyph: `<line x1="9" y1="12" x2="9" y2="20"/><line x1="23" y1="12" x2="23" y2="20"/><line x1="9" y1="16" x2="23" y2="16"/><line x1="16" y1="16" x2="16" y2="22"/><circle cx="16" cy="25" r="1.8" fill="currentColor"/>`,
  },

  // ───────────────────────── Кибер, холбооны сүлжээ (Хавсралт 6) ─────────────────────────
  {
    id: "kiberKK",
    category: "Кибер, холбооны сүлжээ",
    mn: "Кибер аюулгүй байдлын цэргийн удирдлагын байр",
    label: "КК",
    frame: "rect",
    color: "black",
    desc: "Кибер аюулгүй байдлын цэргийн удирдлагын байр.",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "hyanaltHangalalt",
    category: "Кибер, холбооны сүлжээ",
    mn: "Хяналт, хамгаалалтын төв",
    label: "ХХТ",
    frame: "rect",
    color: "black",
    desc: "Хяналт, хамгаалалтын төв.",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "mtTov",
    category: "Кибер, холбооны сүлжээ",
    mn: "Мэдээллийн технологийн төв",
    label: "МТТ",
    frame: "rect",
    color: "black",
    desc: "Мэдээллийн технологийн төв.",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "pc",
    category: "Кибер, холбооны сүлжээ",
    mn: "Компьютер",
    label: "PC",
    frame: "rect",
    color: "black",
    desc: "Компьютер.",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "server",
    category: "Кибер, холбооны сүлжээ",
    mn: "Сервер",
    label: "SRV",
    frame: "rect",
    color: "black",
    desc: "Сервер (файл/вэб/өгөгдлийн сан г.м ерөнхий тэмдэглэгээ).",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "router",
    category: "Кибер, холбооны сүлжээ",
    mn: "Router",
    label: "RTR",
    frame: "point",
    color: "black",
    desc: "Router (чиглүүлэгч).",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "switch",
    category: "Кибер, холбооны сүлжээ",
    mn: "Switch",
    label: "SW",
    frame: "rect",
    color: "black",
    desc: "Switch (шилжүүлэгч).",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "galtHana",
    category: "Кибер, холбооны сүлжээ",
    mn: "Галт хана",
    label: "GW",
    frame: "rect",
    color: "black",
    desc: "Галт хана (firewall).",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "internet",
    category: "Кибер, холбооны сүлжээ",
    mn: "Интернэт",
    label: "NET",
    frame: "point",
    color: "black",
    desc: "Интернэт.",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "wirelessAP",
    category: "Кибер, холбооны сүлжээ",
    mn: "Wireless AP",
    label: "WiFi",
    frame: "rect",
    color: "black",
    desc: "Утасгүй хандалтын цэг (Wireless AP/Router).",
    ref: "Т4-2022 Хавсралт 6",
  },

  // ───────────────────────── Хил, дотоод, онцгой байдал (§16) ─────────────────────────
  {
    id: "hilOtryad",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хилийн отряд",
    label: "ХО",
    frame: "rect",
    color: "green",
    desc: "Хилийн отряд анги, тусгай салбарын байрлал.",
    ref: "Т4-2022 §16.1",
  },
  {
    id: "hilZastav",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хилийн застав",
    label: "ЗАСТАВ",
    frame: "point",
    color: "green",
    desc: "Хилийн застав (дугаар, нэрээр тэмдэглэнэ).",
    ref: "Т4-2022 §16.1",
  },
  {
    id: "hilBoomt",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хилийн боомт",
    label: "БООМТ",
    frame: "point",
    color: "green",
    desc: "Хилийн боомт — ОУ (олон улсын), ХТ (хоёр талын), ТУ (түр/улирлын), ДӨ (дамжин өнгөрөх).",
    ref: "Т4-2022 §16.1",
  },
  {
    id: "hilHaruul",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хилийн харуул",
    label: "ХАРУУЛ",
    frame: "arrow",
    color: "green",
    desc: "Хилийн харуул — БХХ (байнгын), ТХХ (түр), ХХХ (хүчжүүлсэн).",
    ref: "Т4-2022 §16.1",
    approximate: true,
  },
  {
    id: "avragTusgaiAng",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Аврах тусгай ангийн удирдлагын байр",
    label: "АТА",
    frame: "rect",
    color: "orange",
    desc: "Аврах тусгай ангийн удирдлагын байр.",
    ref: "Т4-2022 §16.2",
  },
  {
    id: "aimagUdirdlaga",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Аймаг, нийслэлийн удирдлагын байр",
    label: "АНУБ",
    frame: "rect",
    color: "orange",
    desc: "Аймаг, нийслэлийн онцгой байдлын удирдлагын байр.",
    ref: "Т4-2022 §16.2",
  },
  {
    id: "avragchGalSonoogch",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Аврагч гал сөнөөгч",
    label: "АГС",
    frame: "point",
    color: "orange",
    desc: "Аврагч гал сөнөөгч.",
    ref: "Т4-2022 §16.2",
  },
  {
    id: "tsegCEG",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Цагдаагийн ерөнхий газар",
    label: "ЦЕГ",
    frame: "rect",
    color: "tan",
    desc: "Цагдаагийн ерөнхий газар.",
    ref: "Т4-2022 §16.3",
  },
  {
    id: "dotoodynTsergAngi",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Дотоодын цэргийн анги, хороо",
    label: "ДЦ",
    frame: "rect",
    color: "tan",
    echelon: "III",
    desc: "Дотоодын цэргийн анги, хороо.",
    ref: "Т4-2022 §16.3",
  },
  {
    id: "tsagdaaTasag",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Цагдаагийн тасаг, хэсэг",
    label: "ЦАГ",
    frame: "point",
    color: "tan",
    desc: "Цагдаагийн тасаг, хэсэг, Дотоодын цэргийн тусгай салбар, тасаг.",
    ref: "Т4-2022 §16.3",
  },
  {
    id: "shuuh",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Шүүхийн байгууллага",
    label: "ШҮҮХ",
    frame: "rect",
    color: "tan",
    desc: "Шүүхийн байгууллагууд (ДШ — Дээд шүүх, СуДШ — Сум дундын шүүх).",
    ref: "Т4-2022 §16.3",
  },
  {
    id: "ergeel",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хэв журам сахиулах эргүүл",
    label: "ЭРГ",
    frame: "point",
    color: "tan",
    desc: "Хэв журам сахиулах эргүүл.",
    ref: "Т4-2022 §16.3",
  },
  {
    id: "hodolgoonZohitsuulah",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хөдөлгөөн зохицуулах пост",
    label: "P",
    frame: "circle",
    color: "tan",
    desc: "Хөдөлгөөн зохицуулах пост.",
    ref: "Т4-2022 §16.3",
  },
];

export function getSymbol(id: string): SymbolDef | undefined {
  return SYMBOLS.find((s) => s.id === id);
}
