import type { SymbolDef } from "@/types/symbol";

export const CATEGORIES = [
  "Удирдлага, командын байр",
  "Анги, салбар",
  "Салаа, тасаг, нэгж",
  "Төрөл, мэргэжлийн цэрэг",
  "Ажиллагаа",
  "Гал ба цохилт",
  "Хөдөлгөөн",
  "Явган зэвсэг",
  "Тээврийн хэрэгсэл, техник",
  "Агаарын хэрэгсэл",
  "Кибер, холбооны сүлжээ",
  "Хил, дотоод, онцгой байдал",
] as const;

/**
 * A note appended in the UI (see SymbolTooltip) whenever `approximate` is
 * true: the frame shape / echelon / affiliation color are reproduced exactly
 * from Т4-2022, but the manual's hand-drawn pictorial glyph for this entry
 * could not be recovered from the source PDF's text layer, so a short
 * Mongolian abbreviation stands in for it.
 */
export const APPROXIMATION_NOTE =
  "Хүрээ, шатлал, өнгө нь Т4-2022 зааврын дагуу үнэн зөв; дотоод дүрс нь эх сурвалжийн зурган тэмдгийг орлуулсан товчилсон тэмдэглэгээ.";

export const SYMBOLS: SymbolDef[] = [
  // ───────────────────────── Удирдлага, командын байр (§2.1) ─────────────────────────
  {
    id: "zhzsh",
    category: "Удирдлага, командын байр",
    mn: "Зэвсэгт хүчний Жанжин штаб",
    label: "ЗХЖШ",
    frame: "rect",
    color: "friendly",
    desc: "Монгол Улсын Зэвсэгт хүчний Жанжин штабын удирдлагын байр. Ажлын зураг дээр тэгш өнцөгт хүрээтэй, тугийг фронт руу чиглүүлж зурна.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "bk",
    category: "Удирдлага, командын байр",
    mn: "Бүсийн командлал (цэргийн штаб)",
    label: "БК",
    frame: "rect",
    color: "friendly",
    desc: "Бүсийн командлалын удирдлагын байр (ЦШ — цэргийн штаб).",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "hzck",
    category: "Удирдлага, командын байр",
    mn: "Хуурай замын цэргийн командлал",
    label: "ХЗЦК",
    frame: "rect",
    color: "friendly",
    desc: "Хуурай замын цэргийн командлалын удирдлагын байр.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "thck",
    category: "Удирдлага, командын байр",
    mn: "Тусгай хүчний цэргийн командлал",
    label: "ТХЦК",
    frame: "rect",
    color: "friendly",
    desc: "Тусгай хүчний цэргийн командлалын удирдлагын байр.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "ack",
    category: "Удирдлага, командын байр",
    mn: "Агаарын цэргийн командлал",
    label: "АЦК",
    frame: "rect",
    color: "friendly",
    desc: "Агаарын цэргийн командлалын удирдлагын байр.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "hheg",
    category: "Удирдлага, командын байр",
    mn: "Хил хамгаалахын удирдлагын байгууллага",
    label: "ХХЕГ",
    frame: "rect",
    color: "green",
    desc: "Хил хамгаалалтыг удирдах төрийн захиргааны байгууллага.",
    ref: "Т4-2022 §2.1 / §16.1",
  },
  {
    id: "obeg",
    category: "Удирдлага, командын байр",
    mn: "Онцгой байдлын ерөнхий газар",
    label: "ОБЕГ",
    frame: "rect",
    color: "orange",
    desc: "Онцгой байдлын удирдлагын төв байгууллага.",
    ref: "Т4-2022 §2.1 / §16.2",
  },
  {
    id: "dts",
    category: "Удирдлага, командын байр",
    mn: "Дотоодын цэргийн удирдлагын байгууллага",
    label: "ДЦ",
    frame: "rect",
    color: "tan",
    desc: "Дотоодын цэргийн удирдлагын байгууллагын байр.",
    ref: "Т4-2022 §2.1 / §16.3",
  },
  {
    id: "brigadCP",
    category: "Удирдлага, командын байр",
    mn: "Бригадын командын байр",
    label: "ШТАБ",
    frame: "rect",
    color: "friendly",
    echelon: "X",
    desc: "Холимог бүтэцтэй мотобуудлагын бригадын командын байр. Төрөл мэргэжлийн цэргийн таних тэмдгийг төв хэсэгт зурна.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "horooCP",
    category: "Удирдлага, командын байр",
    mn: "Хорооны командын байр",
    label: "ШТАБ",
    frame: "rect",
    color: "friendly",
    echelon: "III",
    desc: "Хорооны командын байр.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "batalonCP",
    category: "Удирдлага, командын байр",
    mn: "Батальон (дивизион)-ы удирдлагын байр",
    label: "ШТАБ",
    frame: "rect",
    color: "friendly",
    echelon: "II",
    desc: "Батальон (артиллерийн дивизион)-ы удирдлагын байр.",
    ref: "Т4-2022 §2.1",
  },
  {
    id: "rotCP",
    category: "Удирдлага, командын байр",
    mn: "Ротын захирагчийн хянах байр",
    label: "ХБ",
    frame: "triangle",
    color: "friendly",
    echelon: "I",
    desc: "Хяналт/хангалтын байрыг адил хажуут гурвалжин хүрээгээр дүрсэлнэ. Ахлах даргын таних тэмдгийг зурсан үед ротын таних тэмдгийг дахин зурахгүй.",
    ref: "Т4-2022 §2.1 / §1.3",
  },
  {
    id: "salaaCP",
    category: "Удирдлага, командын байр",
    mn: "Салааны захирагчийн хянах байр",
    label: "ХБ",
    frame: "triangle",
    color: "friendly",
    echelon: "c",
    desc: "Салааны захирагчийн хянах байр.",
    ref: "Т4-2022 §2.1",
  },

  // ───────────────────────── Анги, салбар (§2.2) ─────────────────────────
  {
    id: "brigade",
    category: "Анги, салбар",
    mn: "Бригад (явган цэргийн байлдааны машинтай)",
    label: "БР",
    frame: "rect",
    color: "friendly",
    echelon: "X",
    desc: "Төрөл мэргэжлийн буюу суурилсан зэвсэглэл, цэргийн техникийн таних тэмдгээр ялгана.",
    ref: "Т4-2022 §2.2",
    approximate: true,
  },
  {
    id: "horoo",
    category: "Анги, салбар",
    mn: "Хороо (танкийн)",
    label: "ХОР",
    frame: "rect",
    color: "friendly",
    echelon: "III",
    desc: "Хорооны шатлалын тэмдэг III, тэгш өнцөгт хүрээ.",
    ref: "Т4-2022 §2.2",
    approximate: true,
  },
  {
    id: "batalion",
    category: "Анги, салбар",
    mn: "Батальон (хуягт тээвэрлэгчтэй)",
    label: "БАТ",
    frame: "rect",
    color: "friendly",
    echelon: "II",
    desc: "Батальоны шатлалын тэмдэг II, тэгш өнцөгт хүрээ.",
    ref: "Т4-2022 §2.2",
    approximate: true,
  },
  {
    id: "batalionAuto",
    category: "Анги, салбар",
    mn: "Батальон (автомашинтай)",
    label: "БАТ/А",
    frame: "rect",
    color: "friendly",
    echelon: "II",
    desc: "Автомашинтай батальон.",
    ref: "Т4-2022 §2.2",
    approximate: true,
  },
  {
    id: "rot",
    category: "Анги, салбар",
    mn: "Рот (батарей)",
    label: "РОТ",
    frame: "rect",
    color: "friendly",
    echelon: "I",
    desc: "Ротын (батарейн) шатлалын тэмдэг I, тэгш өнцөгт хүрээ.",
    ref: "Т4-2022 §2.2",
    approximate: true,
  },

  // ───────────────────────── Салаа, тасаг, нэгж (§2.3) ─────────────────────────
  {
    id: "salaa",
    category: "Салаа, тасаг, нэгж",
    mn: "Салаа",
    label: "с",
    frame: "rect",
    color: "friendly",
    echelon: "c",
    desc: "Салааны тэмдэглэгээ — зенит, артиллерийн салааг дугуй хүрээгээр тэмдэглэнэ.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "tasag",
    category: "Салаа, тасаг, нэгж",
    mn: "Тасаг (ЯЦБМ-тай)",
    label: "т",
    frame: "rect",
    color: "friendly",
    echelon: "т",
    desc: "ЯЦБМ-тай тасаг.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "buleg",
    category: "Салаа, тасаг, нэгж",
    mn: "Бүлэг (ЯЦБМ-тай)",
    label: "бү",
    frame: "rect",
    color: "friendly",
    echelon: "бү",
    desc: "ЯЦБМ-тай бүлэг.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "gurval",
    category: "Салаа, тасаг, нэгж",
    mn: "Байлдааны гурвал",
    label: "Δ",
    frame: "circle",
    color: "friendly",
    desc: "БД-1/100-ийн 4 дүгээр зүйлийн 4.3 дахь хэсгийг баримтална. Дугуй дүрсийг үүрэг гүйцэтгэх чиглэлд перпендикуляр байрлуулж зурна.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "hos",
    category: "Салаа, тасаг, нэгж",
    mn: "Байлдааны хос",
    label: "хос",
    frame: "circle",
    color: "friendly",
    desc: "БД-1/100-ийн 4 дүгээр зүйлийн 4.1–4.2.6 дахь заалтыг баримтална.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "tsereg",
    category: "Салаа, тасаг, нэгж",
    mn: "Цэрэг (хүн)",
    label: "",
    frame: "circle",
    color: "friendly",
    desc: "Ганц цэргийн байрлалыг дугуй хүрээгээр тэмдэглэнэ.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "olzlogdson",
    category: "Салаа, тасаг, нэгж",
    mn: "Олзлогдсон болон шархадсан цэрэг",
    label: "⊘",
    frame: "circle",
    color: "friendly",
    desc: "Олзлогдсон болон шархадсан цэргийн байрлал.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "alagdsan",
    category: "Салаа, тасаг, нэгж",
    mn: "Алагдсан цэрэг",
    label: "X",
    frame: "circle",
    color: "friendly",
    desc: "Алагдсан цэргийн байрлал.",
    ref: "Т4-2022 §2.3",
  },
  {
    id: "buudagch",
    category: "Салаа, тасаг, нэгж",
    mn: "Буудагч (пулемётчин)",
    label: "БУУ",
    frame: "point",
    color: "friendly",
    desc: "Байлдааны төлөвлөлтөд АКМ, гранатомёт, пулемёт зэрэг нэг бүрийн буудлагын зэвсэглэлийн таних тэмдгээр ялгаж зурна.",
    ref: "Т4-2022 §2.3",
    approximate: true,
  },
  {
    id: "yavganerguul",
    category: "Салаа, тасаг, нэгж",
    mn: "Явган эргүүл",
    label: "ЭРГ",
    frame: "point",
    color: "friendly",
    desc: "Явган эргүүлийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    approximate: true,
  },
  {
    id: "nuutsmanaa",
    category: "Салаа, тасаг, нэгж",
    mn: "Нууц манаа",
    label: "НМ",
    frame: "triangle",
    color: "friendly",
    desc: "Нууц манааны байр.",
    ref: "Т4-2022 §2.3",
    approximate: true,
  },
  {
    id: "tagnuulbuleg",
    category: "Салаа, тасаг, нэгж",
    mn: "Тагнуулын бүлэг",
    label: "ТАГ",
    frame: "point",
    color: "friendly",
    desc: "Тагнуулын бүлгийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    approximate: true,
  },
  {
    id: "dairahotryad",
    category: "Салаа, тасаг, нэгж",
    mn: "Дайрах отряд",
    label: "ДАЙР",
    frame: "point",
    color: "friendly",
    desc: "Дайрах отрядын тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    approximate: true,
  },
  {
    id: "tagnuulotryad",
    category: "Салаа, тасаг, нэгж",
    mn: "Тагнуулын отряд",
    label: "Т.ОТР",
    frame: "point",
    color: "friendly",
    desc: "Тагнуулын отрядын тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    approximate: true,
  },
  {
    id: "tagnuultusgai",
    category: "Салаа, тасаг, нэгж",
    mn: "Тагнуулын тусгай сэргийлэх",
    label: "Т.СЭР",
    frame: "point",
    color: "friendly",
    desc: "Тагнуулын тусгай сэргийлэхийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    approximate: true,
  },
  {
    id: "baildaanytagnuul",
    category: "Салаа, тасаг, нэгж",
    mn: "Байлдааны тагнуулын сэргийлэх",
    label: "Б.ТАГ",
    frame: "point",
    color: "friendly",
    desc: "Байлдааны тагнуулын сэргийлэхийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    approximate: true,
  },
  {
    id: "officertagnuul",
    category: "Салаа, тасаг, нэгж",
    mn: "Офицерын тагнуулын сэргийлэх",
    label: "ОФ",
    frame: "point",
    color: "friendly",
    desc: "Офицерын тагнуулын сэргийлэхийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    approximate: true,
  },
  {
    id: "sergiylehmashine",
    category: "Салаа, тасаг, нэгж",
    mn: "Сэргийлэхийн машин",
    label: "СЭР.М",
    frame: "point",
    color: "friendly",
    desc: "Сэргийлэхийн машины тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    approximate: true,
  },
  {
    id: "yavgansergiyleh",
    category: "Салаа, тасаг, нэгж",
    mn: "Явган сэргийлэх",
    label: "СЭР",
    frame: "point",
    color: "friendly",
    desc: "Явган сэргийлэхийн тэмдэглэгээ.",
    ref: "Т4-2022 §2.3",
    approximate: true,
  },

  // ───────────────────────── Төрөл, мэргэжлийн цэрэг (§2.4) ─────────────────────────
  {
    id: "erhtsereg",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Ерөнхий цэрэг",
    label: "ЕР",
    frame: "ellipse",
    color: "black",
    desc: "Тухайн анги, салбар, нэгжийн суурилсан үндсэн цэргийн техник (ЯЦБМ, хуягт тээвэрлэгч, автомашин)-ийн тэмдгийг хэрэглэнэ.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },
  {
    id: "holimogMB",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Холимог мотобуудлагын салбар",
    label: "МБ",
    frame: "ellipse",
    color: "black",
    desc: "ЯЦБМ, хуягт тээвэрлэгч, автомашинтай холимог мотобуудлагын салбар.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },
  {
    id: "turgenhuchin",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Түргэн байрлах хүчин",
    label: "ТБХ",
    frame: "point",
    color: "black",
    desc: "Түргэн байрлах хүчний тэмдэг. Шатлалын хүрээг ашиглан нэгжийг тодотгоно.",
    ref: "Т4-2022 §2.4 / Хавсралт 1",
    approximate: true,
  },
  {
    id: "tusgaitomilolt",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Тусгай томилолтын анги, салбар",
    label: "ТТ",
    frame: "circle",
    color: "black",
    desc: "Тусгай томилолтын анги, салбарын тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 1",
    approximate: true,
  },
  {
    id: "shuherdesant",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Шүхэр десантын",
    label: "ШД",
    frame: "circle",
    color: "black",
    desc: "Шүхэр десантын батальон/рот/салаа/тасгийн тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 1",
    approximate: true,
  },
  {
    id: "uulyn",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Уулын",
    label: "УУЛ",
    frame: "triangle",
    color: "black",
    desc: "Уулын батальоны тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 1",
    approximate: true,
  },
  {
    id: "tagnuul",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Тагнуул",
    label: "ТАГ",
    frame: "point",
    color: "black",
    desc: "Тагнуулын батальон/ротын ерөнхий тэмдэг.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },
  {
    id: "morьttsereg",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Морьт цэрэг",
    label: "МОР",
    frame: "point",
    color: "black",
    desc: "Морьт цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },
  {
    id: "tank",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Танк",
    label: "ТАНК",
    frame: "diamond",
    color: "black",
    desc: "Танкийн ерөнхий тэмдэг — ромбо хэлбэрийн хүрээ.",
    ref: "Т4-2022 §2.4 / §2.10",
    approximate: true,
  },
  {
    id: "nisehhuchin",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Нисэх хүчин",
    label: "НХ",
    frame: "point",
    color: "black",
    desc: "Агаарын нисэх хүчний ерөнхий тэмдэг.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },
  {
    id: "kiber",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Кибер",
    label: "КИБ",
    frame: "point",
    color: "black",
    desc: "Кибер аюулгүй байдлын цэргийн ерөнхий тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 6",
    approximate: true,
  },
  {
    id: "artilleryEr",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Артиллерийн ерөнхий тэмдэг",
    label: "АРТ",
    frame: "circle",
    color: "black",
    desc: "Артиллерийн цэргийн ерөнхий тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 3",
    approximate: true,
  },
  {
    id: "tsadh",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "ЦАДХ",
    label: "ЦАДХ",
    frame: "point",
    color: "black",
    desc: "Цэрэг-агаарын довтолгооноос хамгаалах цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },
  {
    id: "zenitpuujinart",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Зенитийн пуужин – артиллерийн хосолсон",
    label: "ЗПА",
    frame: "point",
    color: "black",
    desc: "Зенитийн пуужин-артиллерийн хосолсон цогцолборын тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 4",
    approximate: true,
  },
  {
    id: "zenitpuujin",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Зенитийн пуужин",
    label: "ЗП",
    frame: "point",
    color: "black",
    desc: "Зенитийн пуужингийн ерөнхий тэмдэг (Т-тактикийн, ОТ-оператив-тактикийн, ОЦ-олон цэнэгт).",
    ref: "Т4-2022 §2.4 / Хавсралт 4",
    approximate: true,
  },
  {
    id: "rls",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Радиолокацийн станц (РЛС)",
    label: "РЛС",
    frame: "point",
    color: "black",
    desc: "Радиолокацийн станцын ерөнхий тэмдэглэгээ.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },
  {
    id: "holboo",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Холбоо",
    label: "ХОЛ",
    frame: "point",
    color: "black",
    desc: "Холбооны цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 7",
    approximate: true,
  },
  {
    id: "radiotagnuul",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Радио тагнуулын",
    label: "Р.ТАГ",
    frame: "point",
    color: "black",
    desc: "Радио тагнуулын тэмдэг.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },
  {
    id: "medeeleлsetgel",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Мэдээлэл сэтгэл зүйн",
    label: "МСЗ",
    frame: "point",
    color: "black",
    desc: "Мэдээлэл, сэтгэл зүйн хангалтын цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4 / §9",
    approximate: true,
  },
  {
    id: "tsergiinbairzui",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн байр зүй",
    label: "БЗ",
    frame: "triangle",
    color: "black",
    desc: "Цэргийн байр зүйн алба.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },
  {
    id: "hemzhilzui",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Хэмжил зүйн",
    label: "ХЭМЖ",
    frame: "rect",
    color: "black",
    desc: "Цэргийн зэвсэглэл, техникийн хэмжил зүйн алба.",
    ref: "Т4-2022 §2.4 / §41.7",
    approximate: true,
  },
  {
    id: "orionZaiTandalt",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Орон зайн тандалт судалгаа",
    label: "ОЗТ",
    frame: "point",
    color: "black",
    desc: "Орон зайн тандалт судалгааны алба.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },
  {
    id: "tsaguur",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цаг уур",
    label: "ЦУ",
    frame: "point",
    color: "black",
    desc: "Цаг уурын хангалтын алба.",
    ref: "Т4-2022 §2.4 / §40.10",
    approximate: true,
  },
  {
    id: "chb",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цацраг, хими, биологиос хамгаалахын",
    label: "ЦХБ",
    frame: "point",
    color: "black",
    desc: "Цацраг, хими, биологиос хамгаалах цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 5",
    approximate: true,
  },
  {
    id: "tsergiinInj",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн инженер",
    label: "ИНЖ",
    frame: "rect",
    color: "black",
    desc: "Инженерийн цэргийн тэмдэг.",
    ref: "Т4-2022 §2.4 / Хавсралт 6",
    approximate: true,
  },
  {
    id: "guuruus",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Гүүр ус гатлалтын анги, салбар",
    label: "ГҮҮР",
    frame: "point",
    color: "black",
    desc: "Гүүр, ус гатлалтын анги, салбарын тэмдэг.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },
  {
    id: "barilga",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Барилгын анги, салбар",
    label: "БАР",
    frame: "circle",
    color: "black",
    desc: "Барилга, инженерийн цэргийн анги, салбар.",
    ref: "Т4-2022 §2.4 / Хавсралт 11",
    approximate: true,
  },
  {
    id: "materialhang",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Материалын хангалт",
    label: "МАТ",
    frame: "rect",
    color: "black",
    desc: "Материалын хангалтын алба.",
    ref: "Т4-2022 §2.4 / Хавсралт 10",
    approximate: true,
  },
  {
    id: "tsergiinzevsэglэl",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн зэвсэглэл",
    label: "ЗЭВ",
    frame: "point",
    color: "black",
    desc: "Цэргийн зэвсэглэлийн хангалтын алба.",
    ref: "Т4-2022 §2.4 / Хавсралт 11",
    approximate: true,
  },
  {
    id: "tsergiintehnik",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн техникийн",
    label: "ТЕХ",
    frame: "point",
    color: "black",
    desc: "Цэргийн техникийн хангалтын алба.",
    ref: "Т4-2022 §2.4 / Хавсралт 12",
    approximate: true,
  },
  {
    id: "tsergiinhunemn",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн хүн эмнэлэг",
    label: "ЭМ",
    frame: "point",
    color: "black",
    desc: "Цэргийн эрүүл мэндийн хангалтын алба.",
    ref: "Т4-2022 §2.4 / Хавсралт 14",
    approximate: true,
  },
  {
    id: "tsergiintsagdaa",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Цэргийн цагдаа",
    label: "MP",
    frame: "rect",
    color: "tan",
    desc: "Цэргийн цагдаагийн алба (MP — Military Police).",
    ref: "Т4-2022 §2.4",
  },
  {
    id: "oronNutgiinTs",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Орон нутгийн цэрэг",
    label: "ОН",
    frame: "rect",
    color: "brown",
    desc: "Орон нутгийн цэргийн тэмдэг — хүрэн өнгөөр тэмдэглэнэ.",
    ref: "Т4-2022 §2.4 / §1.7.10",
  },
  {
    id: "holimogTbu",
    category: "Төрөл, мэргэжлийн цэрэг",
    mn: "Холимог бүрэлдэхүүнтэй тактикийн бүлэг",
    label: "ТБҮ",
    frame: "circle",
    color: "black",
    desc: "Мото, механик, морьт, орон нутгийн цэрэг гэх мэт холимог бүрэлдэхүүнтэй тактикийн бүлэг.",
    ref: "Т4-2022 §2.4",
    approximate: true,
  },

  // ───────────────────────── Ажиллагаа (§2.5) ─────────────────────────
  {
    id: "otolt",
    category: "Ажиллагаа",
    mn: "Отолт",
    label: "ОТОЛТ",
    frame: "arrow",
    color: "friendly",
    desc: "Дайсны амьд хэл, баримт бичиг, зэвсэглэл, техникийг олзлох зорилгоор жижиг хүчээр гэнэт хийх богино хугацааны ажиллагаа.",
    ref: "Т4-2022 §2.5",
    approximate: true,
  },
  {
    id: "haiguul",
    category: "Ажиллагаа",
    mn: "Хайгуул",
    label: "ХАЙГУУЛ",
    frame: "arrow",
    color: "friendly",
    desc: "Хайгуул хийж буй салбарын ажиллагааны чиглэл.",
    ref: "Т4-2022 §2.5",
    approximate: true,
  },
  {
    id: "merdenhoolt",
    category: "Ажиллагаа",
    mn: "Мөрдөн хөөлт",
    label: "МХ",
    frame: "arrow",
    color: "friendly",
    desc: "Ухарч байгаа дайсныг мөрдөн хөөх ажиллагаа.",
    ref: "Т4-2022 §2.5 / §19.1",
    approximate: true,
  },
  {
    id: "buslэh",
    category: "Ажиллагаа",
    mn: "Бүслэх",
    label: "БҮСЛЭХ",
    frame: "arrow",
    color: "friendly",
    desc: "Дайсны бүлэглэлийг тодорхой чиглэлд бүслэн тусгаарлах ажиллагаа.",
    ref: "Т4-2022 §2.5 / §23",
    approximate: true,
  },
  {
    id: "buslenustgah",
    category: "Ажиллагаа",
    mn: "Бүслэн устгах",
    label: "Б.УСТГАХ",
    frame: "arrow",
    color: "friendly",
    desc: "Бүслэгдсэн дайсны бүлэглэлийг устгах ажиллагаа.",
    ref: "Т4-2022 §2.5 / §23",
    approximate: true,
  },
  {
    id: "orooh",
    category: "Ажиллагаа",
    mn: "Ороох",
    label: "ОРООХ",
    frame: "arrow",
    color: "friendly",
    desc: "Хүч хэрэгслийн ороох маневр.",
    ref: "Т4-2022 §2.5 / §1.2.3",
    approximate: true,
  },
  {
    id: "toiroh",
    category: "Ажиллагаа",
    mn: "Тойрох",
    label: "ТОЙРОХ",
    frame: "arrow",
    color: "friendly",
    desc: "Хүч хэрэгслийн тойрох маневр.",
    ref: "Т4-2022 §2.5 / §1.2.3",
    approximate: true,
  },
  {
    id: "tuiveeh",
    category: "Ажиллагаа",
    mn: "Түйвээх",
    label: "ТҮЙВЭЭХ",
    frame: "arrow",
    color: "friendly",
    desc: "Дайсны байрлалын район, байлдааны журам дотор явуулах түйвээх ажиллагаа.",
    ref: "Т4-2022 §14",
    approximate: true,
  },
  {
    id: "tulgarah",
    category: "Ажиллагаа",
    mn: "Тулгарах",
    label: "ТУЛГАРАХ",
    frame: "arrow",
    color: "friendly",
    desc: "Талууд байлдааны үүргээ давшилтаар шийдвэрлэхийг эрмэлзсэн үед үүсэх тулгарах байлдаан.",
    ref: "Т4-2022 §25",
    approximate: true,
  },
  {
    id: "dairalt",
    category: "Ажиллагаа",
    mn: "Дайралт",
    label: "ДАЙРАЛТ",
    frame: "arrow",
    color: "friendly",
    desc: "Хот, суурин дахь байлдаан, бэхлэгдсэн район, бааз руу давших үеийн дайралт.",
    ref: "Т4-2022 §21.12",
    approximate: true,
  },

  // ───────────────────────── Гал ба цохилт (§2.6) ─────────────────────────
  {
    id: "galynsector",
    category: "Гал ба цохилт",
    mn: "Галын үндсэн сектор",
    label: "ГАЛ",
    frame: "arrow",
    color: "black",
    desc: "Галын хэрэгслийн үндсэн сектор.",
    ref: "Т4-2022 §2.6",
    approximate: true,
  },
  {
    id: "hyralduulsangal",
    category: "Гал ба цохилт",
    mn: "Хуралдуулсан галын зааг",
    label: "ХГ",
    frame: "arrow",
    color: "black",
    desc: "Хуралдуулсан галын зааг.",
    ref: "Т4-2022 §2.6",
    approximate: true,
  },
  {
    id: "hodolgoongui_haalt",
    category: "Гал ба цохилт",
    mn: "Хөдөлгөөнгүй хаалт гал",
    label: "ХГГ",
    frame: "arrow",
    color: "black",
    desc: "Хөдөлгөөнгүй дан хаалт гал.",
    ref: "Т4-2022 §2.6",
    approximate: true,
  },
  {
    id: "daraalanhyral",
    category: "Гал ба цохилт",
    mn: "Дараалан хуралдуулсан гал",
    label: "ДХГ",
    frame: "arrow",
    color: "black",
    desc: "Дараалан хуралдуулсан гал.",
    ref: "Т4-2022 §2.6",
    approximate: true,
  },
  {
    id: "nisehongots_str",
    category: "Гал ба цохилт",
    mn: "Нисэх онгоцны цохилт",
    label: "ОНГОЦ",
    frame: "arrow",
    color: "friendly",
    desc: "Онгоцны төрөл, огноо, цаг минутыг тэмдэглэнэ.",
    ref: "Т4-2022 §2.6",
    approximate: true,
  },
  {
    id: "nisdegtereg_str",
    category: "Гал ба цохилт",
    mn: "Нисдэг тэрэгний цохилт",
    label: "Н.ТЭРЭГ",
    frame: "arrow",
    color: "friendly",
    desc: "Нисдэг тэрэгний төрөл, огноо, цаг минутыг тэмдэглэнэ.",
    ref: "Т4-2022 §2.6",
    approximate: true,
  },
  {
    id: "puujin_str",
    category: "Гал ба цохилт",
    mn: "Пуужингийн цохилт",
    label: "ПУУЖИН",
    frame: "circle",
    color: "friendly",
    desc: "Пуужингийн цохилтын тэмдэглэгээ.",
    ref: "Т4-2022 §2.6",
    approximate: true,
  },
  {
    id: "tsomiin_str",
    category: "Гал ба цохилт",
    mn: "Цөмийн цохилт",
    label: "ЦӨМ",
    frame: "circle",
    color: "friendly",
    desc: "Цөмийн цохилтын тэмдэглэгээ.",
    ref: "Т4-2022 §2.6",
    approximate: true,
  },
  {
    id: "tsomiinEsrэg",
    category: "Гал ба цохилт",
    mn: "Эсрэг талын цөмийн цохилт хийж болзошгүй цэг",
    label: "ЦӨМ?",
    frame: "circle",
    color: "hostile",
    desc: "Эсрэг талын цөмийн цохилт хийж болзошгүй гэж тооцоолсон цэг.",
    ref: "Т4-2022 §2.6",
    approximate: true,
  },

  // ───────────────────────── Хөдөлгөөн (§2.7) ─────────────────────────
  {
    id: "udirdlagynBairynHodolgoon",
    category: "Хөдөлгөөн",
    mn: "Удирдлагын байрын хөдөлгөөн (аяны журманд)",
    label: "УБ",
    frame: "arrow",
    color: "friendly",
    desc: "Удирдлагын байрын аяны журмын хөдөлгөөн.",
    ref: "Т4-2022 §2.7",
    approximate: true,
  },
  {
    id: "horoonyDavshilt",
    category: "Хөдөлгөөн",
    mn: "Хорооны давшилт",
    label: "→",
    frame: "arrow",
    color: "friendly",
    echelon: "III",
    desc: "Хорооны давшилтын чиглэл.",
    ref: "Т4-2022 §2.7",
    approximate: true,
  },
  {
    id: "batalonyDavshilt",
    category: "Хөдөлгөөн",
    mn: "Батальоны давшилт",
    label: "→",
    frame: "arrow",
    color: "friendly",
    echelon: "II",
    desc: "Батальоны давшилтын чиглэл.",
    ref: "Т4-2022 §2.7",
    approximate: true,
  },
  {
    id: "rotynDavshilt",
    category: "Хөдөлгөөн",
    mn: "Ротын давшилт",
    label: "→",
    frame: "arrow",
    color: "friendly",
    echelon: "I",
    desc: "Ротын давшилтын чиглэл.",
    ref: "Т4-2022 §2.7",
    approximate: true,
  },
  {
    id: "tomorzam",
    category: "Хөдөлгөөн",
    mn: "Цэргийг төмөр замаар тээвэрлэх",
    label: "Т/З",
    frame: "point",
    color: "black",
    desc: "Цэргийг төмөр замаар тээвэрлэх тэмдэглэгээ.",
    ref: "Т4-2022 §2.7",
    approximate: true,
  },
  {
    id: "agaaraar",
    category: "Хөдөлгөөн",
    mn: "Цэргийг агаараар тээвэрлэх",
    label: "АГААР",
    frame: "point",
    color: "friendly",
    desc: "Цэргийг агаараар тээвэрлэх тэмдэглэгээ.",
    ref: "Т4-2022 §2.7",
    approximate: true,
  },

  // ───────────────────────── Явган зэвсэг (§2.10 Хүснэгт 13) ─────────────────────────
  {
    id: "avtomat",
    category: "Явган зэвсэг",
    mn: "Автомат, винтов",
    label: "АК",
    frame: "point",
    color: "black",
    desc: "Автомат буу/винтовын тэмдэг.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    approximate: true,
  },
  {
    id: "granatAvtomat",
    category: "Явган зэвсэг",
    mn: "Гранат шидэгчтэй автомат",
    label: "АК+Г",
    frame: "point",
    color: "black",
    desc: "Гранат шидэгч бүхий автомат.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    approximate: true,
  },
  {
    id: "avtomatGranatomyot",
    category: "Явган зэвсэг",
    mn: "Автомат гранат шидэгч",
    label: "АГС",
    frame: "point",
    color: "black",
    desc: "Автомат гранат шидэгч (АГС).",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    approximate: true,
  },
  {
    id: "hagasAvtomatGranatomyot",
    category: "Явган зэвсэг",
    mn: "Хагас автомат гранат шидэгч",
    label: "ХАГС",
    frame: "point",
    color: "black",
    desc: "Хагас автомат гранат шидэгч.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    approximate: true,
  },
  {
    id: "mergenBuudagch",
    category: "Явган зэвсэг",
    mn: "Мэргэн буудагчийн винтов",
    label: "СВД",
    frame: "point",
    color: "black",
    desc: "Мэргэн буудагчийн винтов.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    approximate: true,
  },
  {
    id: "tasgiinPulemyot",
    category: "Явган зэвсэг",
    mn: "Тасгийн пулемёт",
    label: "РПК",
    frame: "point",
    color: "black",
    desc: "Тасгийн пулемёт.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    approximate: true,
  },
  {
    id: "rotynPulemyot",
    category: "Явган зэвсэг",
    mn: "Ротын пулемёт",
    label: "ПК",
    frame: "point",
    color: "black",
    desc: "Ротын пулемёт.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    approximate: true,
  },
  {
    id: "garGranatomyot",
    category: "Явган зэвсэг",
    mn: "Гар гранатомёт",
    label: "РПГ",
    frame: "point",
    color: "black",
    desc: "Гар гранатомёт.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    approximate: true,
  },
  {
    id: "suuurtGranatomyot",
    category: "Явган зэвсэг",
    mn: "Суурьт гранатомёт",
    label: "СПГ",
    frame: "point",
    color: "black",
    desc: "Суурьт гранатомёт.",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    approximate: true,
  },
  {
    id: "avtomatGranatomyot2",
    category: "Явган зэвсэг",
    mn: "Автомат гранатомёт",
    label: "АГС-17",
    frame: "point",
    color: "black",
    desc: "Автомат гранатомёт (жишээ нь АГС-17).",
    ref: "Т4-2022 §2.10 Хүснэгт 13",
    approximate: true,
  },

  // ───────────────────────── Тээврийн хэрэгсэл, техник (§2.10 Хүснэгт 14–15) ─────────────────────────
  {
    id: "tankAT",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "85мм хүртэлх калибрын танк эсэргүүцэх буу",
    label: "ТЭБ-85",
    frame: "point",
    color: "black",
    desc: "85мм хүртэлх калибрын танк эсэргүүцэх буу.",
    ref: "Т4-2022 §2.10 Хүснэгт 14",
    approximate: true,
  },
  {
    id: "tankAT2",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "100мм хүртэлх калибрын танк эсэргүүцэх их буу",
    label: "ТЭБ-100",
    frame: "point",
    color: "black",
    desc: "100мм хүртэлх калибрын танк эсэргүүцэх их буу.",
    ref: "Т4-2022 §2.10 Хүснэгт 14",
    approximate: true,
  },
  {
    id: "tankATzaluurt",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Танк эсэргүүцэх залуурт пуужин",
    label: "ТЭЗП",
    frame: "point",
    color: "black",
    desc: "Танк эсэргүүцэх залуурт пуужин.",
    ref: "Т4-2022 §2.10 Хүснэгт 14",
    approximate: true,
  },
  {
    id: "yatsBM",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Явган цэргийн байлдааны машин (ЯЦБМ)",
    label: "ЯЦБМ",
    frame: "rect",
    color: "friendly",
    desc: "Явган цэргийн байлдааны машин.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "huyagtTeeverlegch",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Хуягт тээвэрлэгч",
    label: "ХТ",
    frame: "rect",
    color: "friendly",
    desc: "Хуягт тээвэрлэгч.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "tankIcon",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Танк",
    label: "ТАНК",
    frame: "diamond",
    color: "friendly",
    desc: "Танкийн ерөнхий тэмдэг.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "tankZahiragch",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Танк (захирагчийн)",
    label: "ТАНК-З",
    frame: "diamond",
    color: "friendly",
    desc: "Захирагчийн танк.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "hovogchTank",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Хөвөгч танк",
    label: "ТАНК-Х",
    frame: "diamond",
    color: "friendly",
    desc: "Хөвөгч танк.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "ognyometTank",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Огнёмёттой танк",
    label: "ТАНК-О",
    frame: "diamond",
    color: "friendly",
    desc: "Огнёмёттой танк.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "minTrallTank",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Минийн тралл зүүсэн танк",
    label: "ТАНК-МТ",
    frame: "diamond",
    color: "friendly",
    desc: "Минийн тралл зүүсэн танк.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "buldozerTank",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Бульдозертой танк",
    label: "ТАНК-Б",
    frame: "diamond",
    color: "friendly",
    desc: "Бульдозертой танк.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "avtomashin",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Автомашин",
    label: "АВТО",
    frame: "rect",
    color: "black",
    desc: "Автомашин.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "huyaglasanAvto",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Хуягласан автомашин",
    label: "АВТО-Х",
    frame: "rect",
    color: "black",
    desc: "Хуягласан автомашин.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "mototsikл",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Мотоцикл",
    label: "МЦ",
    frame: "point",
    color: "black",
    desc: "Мотоцикл.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "gemtelteiTehnik",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Гэмтэлтэй техник",
    label: "ГЭМТ",
    frame: "diamond",
    color: "hostile",
    desc: "Гэмтэлтэй/эвдэрсэн техник — улаан өнгөөр олзолсон техникийг тэмдэглэнэ.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },
  {
    id: "sergeenBosgohBoлomжgui",
    category: "Тээврийн хэрэгсэл, техник",
    mn: "Сэргээн босгох боломжгүй техник",
    label: "Х",
    frame: "diamond",
    color: "hostile",
    desc: "Сэргээн босгох боломжгүй техник.",
    ref: "Т4-2022 §2.10 Хүснэгт 15",
    approximate: true,
  },

  // ───────────────────────── Агаарын хэрэгсэл (§2.10 Хүснэгт 16) ─────────────────────────
  {
    id: "dairagchOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Дайрагч онгоц",
    label: "ДАЙР",
    frame: "point",
    color: "friendly",
    desc: "Дайрагч онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },
  {
    id: "sonyogchOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Сөнөөгч онгоц",
    label: "СӨН",
    frame: "point",
    color: "friendly",
    desc: "Сөнөөгч онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },
  {
    id: "bombogdogchOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Бөмбөгдөгч онгоц",
    label: "БӨМБ",
    frame: "point",
    color: "friendly",
    desc: "Бөмбөгдөгч онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },
  {
    id: "tagnuulynOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Тагнуулын онгоц",
    label: "Т.ОНГ",
    frame: "point",
    color: "friendly",
    desc: "Тагнуулын онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },
  {
    id: "teevrinOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Тээврийн онгоц",
    label: "Т/О",
    frame: "point",
    color: "friendly",
    desc: "Тээврийн онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },
  {
    id: "rtsOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Радио цахим тэмцлийн онгоц",
    label: "РЦТ",
    frame: "point",
    color: "friendly",
    desc: "Радио цахим тэмцлийн онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },
  {
    id: "irgeniinOngots",
    category: "Агаарын хэрэгсэл",
    mn: "Иргэний онгоц",
    label: "ИРГ",
    frame: "point",
    color: "black",
    desc: "Иргэний онгоц.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },
  {
    id: "baildaanyNisdegTereg",
    category: "Агаарын хэрэгсэл",
    mn: "Байлдааны нисдэг тэрэг",
    label: "Н/Т",
    frame: "point",
    color: "friendly",
    desc: "Байлдааны нисдэг тэрэг.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },
  {
    id: "tagnuulynNisdegTereg",
    category: "Агаарын хэрэгсэл",
    mn: "Тагнуулын нисдэг тэрэг",
    label: "Т.Н/Т",
    frame: "point",
    color: "friendly",
    desc: "Тагнуулын нисдэг тэрэг.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },
  {
    id: "teevriinNisdegTereg",
    category: "Агаарын хэрэгсэл",
    mn: "Тээврийн нисдэг тэрэг",
    label: "Тр.Н/Т",
    frame: "point",
    color: "friendly",
    desc: "Тээврийн нисдэг тэрэг.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },
  {
    id: "nisgegchgui",
    category: "Агаарын хэрэгсэл",
    mn: "Нисгэгчгүй нисэх хэрэгсэл",
    label: "НГ",
    frame: "point",
    color: "black",
    desc: "Нисгэгчгүй нисэх хэрэгсэл (дрон).",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },
  {
    id: "tagnuulynNisgegchgui",
    category: "Агаарын хэрэгсэл",
    mn: "Тагнуулын нисгэгчгүй нисэх хэрэгсэл",
    label: "Т.НГ",
    frame: "point",
    color: "black",
    desc: "Тагнуулын нисгэгчгүй нисэх хэрэгсэл.",
    ref: "Т4-2022 §2.10 Хүснэгт 16",
    approximate: true,
  },

  // ───────────────────────── Кибер, холбооны сүлжээ (Хавсралт 6) ─────────────────────────
  {
    id: "kiberKK",
    category: "Кибер, холбооны сүлжээ",
    mn: "Кибер аюулгүй байдлын цэргийн удирдлагын байр",
    label: "КК",
    frame: "rect",
    color: "black",
    desc: "Кибер аюулгүй байдлын цэргийн удирдлагын байр.",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "hyanaltHangalalt",
    category: "Кибер, холбооны сүлжээ",
    mn: "Хяналт, хамгаалалтын төв",
    label: "ХХТ",
    frame: "rect",
    color: "black",
    desc: "Хяналт, хамгаалалтын төв.",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "mtTov",
    category: "Кибер, холбооны сүлжээ",
    mn: "Мэдээллийн технологийн төв",
    label: "МТТ",
    frame: "rect",
    color: "black",
    desc: "Мэдээллийн технологийн төв.",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "pc",
    category: "Кибер, холбооны сүлжээ",
    mn: "Компьютер",
    label: "PC",
    frame: "rect",
    color: "black",
    desc: "Компьютер.",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "server",
    category: "Кибер, холбооны сүлжээ",
    mn: "Сервер",
    label: "SRV",
    frame: "rect",
    color: "black",
    desc: "Сервер (файл/вэб/өгөгдлийн сан г.м ерөнхий тэмдэглэгээ).",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "router",
    category: "Кибер, холбооны сүлжээ",
    mn: "Router",
    label: "RTR",
    frame: "point",
    color: "black",
    desc: "Router (чиглүүлэгч).",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "switch",
    category: "Кибер, холбооны сүлжээ",
    mn: "Switch",
    label: "SW",
    frame: "rect",
    color: "black",
    desc: "Switch (шилжүүлэгч).",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "galtHana",
    category: "Кибер, холбооны сүлжээ",
    mn: "Галт хана",
    label: "GW",
    frame: "rect",
    color: "black",
    desc: "Галт хана (firewall).",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "internet",
    category: "Кибер, холбооны сүлжээ",
    mn: "Интернэт",
    label: "NET",
    frame: "point",
    color: "black",
    desc: "Интернэт.",
    ref: "Т4-2022 Хавсралт 6",
  },
  {
    id: "wirelessAP",
    category: "Кибер, холбооны сүлжээ",
    mn: "Wireless AP",
    label: "WiFi",
    frame: "rect",
    color: "black",
    desc: "Утасгүй хандалтын цэг (Wireless AP/Router).",
    ref: "Т4-2022 Хавсралт 6",
  },

  // ───────────────────────── Хил, дотоод, онцгой байдал (§16) ─────────────────────────
  {
    id: "hilOtryad",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хилийн отряд",
    label: "ХО",
    frame: "rect",
    color: "green",
    desc: "Хилийн отряд анги, тусгай салбарын байрлал.",
    ref: "Т4-2022 §16.1",
  },
  {
    id: "hilZastav",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хилийн застав",
    label: "ЗАСТАВ",
    frame: "point",
    color: "green",
    desc: "Хилийн застав (дугаар, нэрээр тэмдэглэнэ).",
    ref: "Т4-2022 §16.1",
  },
  {
    id: "hilBoomt",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хилийн боомт",
    label: "БООМТ",
    frame: "point",
    color: "green",
    desc: "Хилийн боомт — ОУ (олон улсын), ХТ (хоёр талын), ТУ (түр/улирлын), ДӨ (дамжин өнгөрөх).",
    ref: "Т4-2022 §16.1",
  },
  {
    id: "hilHaruul",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хилийн харуул",
    label: "ХАРУУЛ",
    frame: "arrow",
    color: "green",
    desc: "Хилийн харуул — БХХ (байнгын), ТХХ (түр), ХХХ (хүчжүүлсэн).",
    ref: "Т4-2022 §16.1",
    approximate: true,
  },
  {
    id: "avragTusgaiAng",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Аврах тусгай ангийн удирдлагын байр",
    label: "АТА",
    frame: "rect",
    color: "orange",
    desc: "Аврах тусгай ангийн удирдлагын байр.",
    ref: "Т4-2022 §16.2",
  },
  {
    id: "aimagUdirdlaga",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Аймаг, нийслэлийн удирдлагын байр",
    label: "АНУБ",
    frame: "rect",
    color: "orange",
    desc: "Аймаг, нийслэлийн онцгой байдлын удирдлагын байр.",
    ref: "Т4-2022 §16.2",
  },
  {
    id: "avragchGalSonoogch",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Аврагч гал сөнөөгч",
    label: "АГС",
    frame: "point",
    color: "orange",
    desc: "Аврагч гал сөнөөгч.",
    ref: "Т4-2022 §16.2",
  },
  {
    id: "tsegCEG",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Цагдаагийн ерөнхий газар",
    label: "ЦЕГ",
    frame: "rect",
    color: "tan",
    desc: "Цагдаагийн ерөнхий газар.",
    ref: "Т4-2022 §16.3",
  },
  {
    id: "dotoodynTsergAngi",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Дотоодын цэргийн анги, хороо",
    label: "ДЦ",
    frame: "rect",
    color: "tan",
    echelon: "III",
    desc: "Дотоодын цэргийн анги, хороо.",
    ref: "Т4-2022 §16.3",
  },
  {
    id: "tsagdaaTasag",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Цагдаагийн тасаг, хэсэг",
    label: "ЦАГ",
    frame: "point",
    color: "tan",
    desc: "Цагдаагийн тасаг, хэсэг, Дотоодын цэргийн тусгай салбар, тасаг.",
    ref: "Т4-2022 §16.3",
  },
  {
    id: "shuuh",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Шүүхийн байгууллага",
    label: "ШҮҮХ",
    frame: "rect",
    color: "tan",
    desc: "Шүүхийн байгууллагууд (ДШ — Дээд шүүх, СуДШ — Сум дундын шүүх).",
    ref: "Т4-2022 §16.3",
  },
  {
    id: "ergeel",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хэв журам сахиулах эргүүл",
    label: "ЭРГ",
    frame: "point",
    color: "tan",
    desc: "Хэв журам сахиулах эргүүл.",
    ref: "Т4-2022 §16.3",
  },
  {
    id: "hodolgoonZohitsuulah",
    category: "Хил, дотоод, онцгой байдал",
    mn: "Хөдөлгөөн зохицуулах пост",
    label: "P",
    frame: "circle",
    color: "tan",
    desc: "Хөдөлгөөн зохицуулах пост.",
    ref: "Т4-2022 §16.3",
  },
];

export function getSymbol(id: string): SymbolDef | undefined {
  return SYMBOLS.find((s) => s.id === id);
}
